"""Does the Postgres schema contain everything the application's SQL needs? Checked without any database server, by reading every SQL
statement out of app/*.py and comparing it with SCHEMA: tables, columns, required (NOT NULL) columns on inserts, upsert targets,
and the keys, cascades and constraints the code relies on."""
import ast
import re
from pathlib import Path

import pytest

from app.database import SCHEMA, SCHEMA_UPGRADES

APP = Path(__file__).resolve().parent.parent / "app"
SQL_START = re.compile(r"^\s*(?:--[^\n]*\n\s*)*(SELECT\b|INSERT\s+INTO\b|UPDATE\s+\w+\s+SET\b|DELETE\s+FROM\b|WITH\s+\w+\s+AS\s*\()", re.I)
KEYWORDS = set("""select from where and or not null is in as on join left right inner outer order by group having limit offset insert into values update set
delete conflict do nothing excluded returning exists case when then else end distinct count sum avg min max lower upper like escape desc asc union all
true false between current_timestamp coalesce cast length over partition""".split())


def schema():
    """{table: {"cols": {name: {...}}, "unique": [sets of columns], "pk": set, "fks": [(col, table, col)]}} parsed from SCHEMA."""
    text = re.sub(r"--[^\n]*", "", SCHEMA)
    out = {}
    for m in re.finditer(r"CREATE TABLE IF NOT EXISTS (\w+) \((.*?)\n\);", text, re.S):
        table, body = m.group(1), m.group(2)
        cols, unique, pk, fks = {}, [], set(), []
        for line in [x.strip().rstrip(",") for x in body.split("\n") if x.strip()]:
            if line.startswith("PRIMARY KEY"):
                pk = {c.strip() for c in re.search(r"\((.*)\)", line).group(1).split(",")}
                continue
            name, rest = line.split(None, 1)
            identity = "GENERATED BY DEFAULT AS IDENTITY" in rest
            cols[name] = {"notnull": "NOT NULL" in rest or "PRIMARY KEY" in rest, "default": "DEFAULT" in rest or identity}
            if "PRIMARY KEY" in rest:
                pk = {name}
            if "UNIQUE" in rest:
                unique.append({name})
            ref = re.search(r"REFERENCES (\w+)\((\w+)\)", rest)
            if ref:
                fks.append((name, ref.group(1), ref.group(2)))
        for c in pk:
            cols[c]["notnull"] = True
        out[table] = {"cols": cols, "unique": unique, "pk": pk, "fks": fks}
    for m in re.finditer(r"CREATE UNIQUE INDEX IF NOT EXISTS \w+\s+ON (\w+)\s*\(([^)]*)\)(\s+WHERE)?", text):
        if not m.group(3):                                   # a partial unique index is not a valid ON CONFLICT target on its own
            out[m.group(1)]["unique"].append({c.strip() for c in m.group(2).split(",")})
    return out


def sql_statements():
    """(file, line, sql) for every string in app/*.py that is SQL. f-string pieces are joined with a placeholder for the dynamic part."""
    found = []
    for path in sorted(APP.rglob("*.py")):
        if path.name in ("database.py",):                    # the schema itself is checked elsewhere
            continue
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            text = None
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                text = node.value
            elif isinstance(node, ast.JoinedStr):
                text = "".join(p.value if isinstance(p, ast.Constant) else "{x}" for p in node.values)
            if text and SQL_START.match(text) and re.search(r"\b(FROM|INTO|UPDATE|SET)\b", text, re.I):
                found.append((path.relative_to(APP).as_posix(), node.lineno, text))
    return found


def tables_in(sql):
    """{alias_or_name: table} for every table the statement names."""
    refs = {}
    for m in re.finditer(r"(?<!DO\s)\b(?:FROM|JOIN|INTO|UPDATE)\s+(\w+)(?:\s+(?:AS\s+)?(?!(?:WHERE|SET|ON|JOIN|LEFT|INNER|ORDER|GROUP|LIMIT|VALUES|AND|USING|SELECT)\b)(\w+))?", sql, re.I):
        table, alias = m.group(1), m.group(2)
        refs[table.lower()] = table.lower()
        if alias:
            refs[alias.lower()] = table.lower()
    return refs


STATEMENTS = sql_statements()
SCH = schema()


def test_the_extractor_finds_the_applications_sql():
    assert len(STATEMENTS) > 80, f"only {len(STATEMENTS)} statements found: the extractor is broken"
    assert {f for f, _, _ in STATEMENTS} >= {"services/candidate_service.py", "services/auth_service.py", "routes/upload.py", "llm/query_tools.py"}


def test_every_table_the_sql_names_exists():
    missing = []
    for f, line, sql in STATEMENTS:
        for alias, table in tables_in(sql).items():
            if table in ("{x}", "x") or "{x}" in table:
                continue                                      # dynamic table name (the whitelisted database viewer)
            if table not in SCH:
                missing.append((f, line, table))
    assert not missing, missing


def test_every_column_written_or_referenced_with_a_table_prefix_exists():
    problems = []
    for f, line, sql in STATEMENTS:
        refs = tables_in(sql)
        for alias, col in re.findall(r"\b([a-z]\w*)\.([a-z_]\w*)\b", sql):
            table = refs.get(alias)
            if table and table in SCH and col not in SCH[table]["cols"] and col != "*":
                problems.append((f, line, f"{alias}.{col}", table))
    assert not problems, problems


def test_insert_column_lists_name_real_columns_and_supply_every_required_one():
    problems = []
    for f, line, sql in STATEMENTS:
        m = re.match(r"\s*INSERT\s+INTO\s+(\w+)\s*\(([^)]*)\)", sql, re.I)
        if not m or m.group(1) not in SCH:
            continue
        table, cols = m.group(1), [c.strip() for c in m.group(2).split(",")]
        unknown = [c for c in cols if c not in SCH[table]["cols"]]
        required = [c for c, v in SCH[table]["cols"].items() if v["notnull"] and not v["default"] and c not in cols]
        if unknown or required:
            problems.append((f, line, table, {"unknown": unknown, "missing_required": required}))
    assert not problems, problems


def test_update_set_lists_name_real_columns():
    problems = []
    for f, line, sql in STATEMENTS:
        m = re.match(r"\s*UPDATE\s+(\w+)\s+SET\s+(.*?)(?:\s+WHERE\b|$)", sql, re.I | re.S)
        if not m or m.group(1) not in SCH:
            continue
        table = m.group(1)
        for col in re.findall(r"(?:^|,)\s*(\w+)\s*=", m.group(2)):
            if col not in SCH[table]["cols"]:
                problems.append((f, line, table, col))
    assert not problems, problems


def test_single_table_statements_only_use_real_columns():
    """Plain `WHERE col = ?` style conditions in statements that touch one table."""
    problems = []
    for f, line, sql in STATEMENTS:
        refs = tables_in(sql)
        tables = set(refs.values())
        if len(tables) != 1 or "{x}" in sql or next(iter(tables)) not in SCH:
            continue
        table = next(iter(tables))
        cleaned = re.sub(r"'[^']*'", "''", sql)
        for col in re.findall(r"\b([a-z_]\w*)\s*(?:=|!=|<>|>=|<=|>|<|\bLIKE\b|\bIS\b|\bIN\b)", cleaned, re.I):
            low = col.lower()
            if low in KEYWORDS or low in SCH[table]["cols"] or low in refs:
                continue
            if re.search(rf"\bAS\s+{low}\b", cleaned, re.I) or re.search(rf"\b{low}\s*\(", cleaned, re.I):
                continue
            problems.append((f, line, table, col))
    assert not problems, problems


def test_upsert_targets_are_real_unique_keys():
    seen = 0
    for f, line, sql in STATEMENTS:
        m = re.search(r"INSERT\s+INTO\s+(\w+).*?ON\s+CONFLICT\s*\(([^)]*)\)", sql, re.I | re.S)
        if not m:
            continue
        seen += 1
        table, target = m.group(1), {c.strip() for c in m.group(2).split(",")}
        keys = SCH[table]["unique"] + ([SCH[table]["pk"]] if SCH[table]["pk"] else [])
        assert target in keys, f"{f}:{line} ON CONFLICT ({', '.join(sorted(target))}) on {table} has no matching unique key"
    assert seen >= 3          # analysis_results, skill_aliases, ai_usage


def test_inserts_into_tables_without_an_id_column_do_not_expect_one():
    from app.db import ID_TABLES
    for table, info in SCH.items():
        has_id = "id" in info["cols"]
        assert (table in ID_TABLES) == has_id, f"{table}: ID_TABLES and the schema disagree about having an id column"


def test_keys_and_cascades_the_code_relies_on():
    """Behaviours the app depends on, each tied to a constraint that must exist."""
    # deleting a job removes its skills, resumes, scores and chat; deleting a resume removes its skills, chunks, log and score
    for child in ("job_required_skills", "applications", "analysis_results", "chat_history"):
        assert any(fk[1] == "job_descriptions" for fk in SCH[child]["fks"]), child
    for child in ("application_skills", "resume_chunks", "verification_log", "analysis_results"):
        assert any(fk[1] == "applications" for fk in SCH[child]["fks"]), child
    assert any(fk[1] == "candidates" for fk in SCH["applications"]["fks"])
    # accounts and candidates are unique by email, a score is unique per resume
    assert {"email"} in SCH["users"]["unique"] and {"email"} in SCH["candidates"]["unique"] and {"application_id"} in SCH["analysis_results"]["unique"]
    assert SCH["skill_aliases"]["pk"] == {"alias"} and SCH["ai_usage"]["pk"] == {"day", "bucket"}
    assert "CHECK (role IN ('admin', 'recruiter'))" in SCHEMA
    assert "uq_active_application" in SCHEMA and "WHERE application_status = 'active'" in SCHEMA      # one active resume per person per job


def test_upgrade_statements_target_real_columns():
    for stmt in SCHEMA_UPGRADES:
        m = re.match(r"ALTER TABLE (\w+) ADD COLUMN IF NOT EXISTS (\w+)", stmt)
        assert m and m.group(2) in SCH[m.group(1)]["cols"], stmt


PINNED_COLUMNS = [      # (table, column, NOT NULL, has a default): verified equal to the live database before SQLite was removed
    ("candidates", "id", True, True),
    ("candidates", "name", False, False),
    ("candidates", "email", False, False),
    ("candidates", "phone", False, False),
    ("candidates", "created_at", True, True),
    ("job_descriptions", "id", True, True),
    ("job_descriptions", "owner_id", False, False),
    ("job_descriptions", "title", False, False),
    ("job_descriptions", "raw_text", False, False),
    ("job_descriptions", "min_experience_years", False, False),
    ("job_descriptions", "soft_skills", False, False),
    ("job_descriptions", "summary", False, False),
    ("job_descriptions", "weights", False, False),
    ("job_descriptions", "cutoffs", False, False),
    ("job_descriptions", "created_at", True, True),
    ("job_required_skills", "id", True, True),
    ("job_required_skills", "job_description_id", True, False),
    ("job_required_skills", "skill_name", True, False),
    ("job_required_skills", "is_gate", True, True),
    ("job_required_skills", "importance", True, True),
    ("applications", "id", True, True),
    ("applications", "candidate_id", True, False),
    ("applications", "job_description_id", True, False),
    ("applications", "resume_filename", False, False),
    ("applications", "resume_hash", True, False),
    ("applications", "raw_text", False, False),
    ("applications", "education", False, False),
    ("applications", "experience_years", False, False),
    ("applications", "experience_detail", False, False),
    ("applications", "internships", False, False),
    ("applications", "soft_skills", False, False),
    ("applications", "profile_json", False, False),
    ("applications", "projects", False, False),
    ("applications", "certifications", False, False),
    ("applications", "extraction_status", True, True),
    ("applications", "verification_status", True, True),
    ("applications", "application_status", True, True),
    ("applications", "created_at", True, True),
    ("application_skills", "id", True, True),
    ("application_skills", "application_id", True, False),
    ("application_skills", "skill_name", True, False),
    ("application_skills", "raw_skill", False, False),
    ("application_skills", "level", False, False),
    ("resume_chunks", "id", True, True),
    ("resume_chunks", "application_id", True, False),
    ("resume_chunks", "chunk_index", True, False),
    ("resume_chunks", "text", True, False),
    ("resume_chunks", "embedding", False, False),
    ("analysis_results", "id", True, True),
    ("analysis_results", "application_id", True, False),
    ("analysis_results", "job_description_id", True, False),
    ("analysis_results", "match_score", False, False),
    ("analysis_results", "skill_match_ratio", False, False),
    ("analysis_results", "component_scores", False, False),
    ("analysis_results", "skill_breakdown", False, False),
    ("analysis_results", "llm_status", False, False),
    ("analysis_results", "matching_skills", False, False),
    ("analysis_results", "missing_skills", False, False),
    ("analysis_results", "strengths", False, False),
    ("analysis_results", "weaknesses", False, False),
    ("analysis_results", "summary", False, False),
    ("analysis_results", "interview_questions", False, False),
    ("analysis_results", "recommendation", False, False),
    ("analysis_results", "created_at", True, True),
    ("verification_log", "id", True, True),
    ("verification_log", "application_id", True, False),
    ("verification_log", "field", True, False),
    ("verification_log", "old_value", False, False),
    ("verification_log", "new_value", False, False),
    ("verification_log", "evidence_quote", False, False),
    ("verification_log", "created_at", True, True),
    ("skill_aliases", "alias", True, False),
    ("skill_aliases", "canonical", True, False),
    ("skill_aliases", "source", True, True),
    ("users", "id", True, True),
    ("users", "email", True, False),
    ("users", "name", True, True),
    ("users", "password_hash", True, False),
    ("users", "role", True, True),
    ("users", "is_active", True, True),
    ("users", "session_epoch", True, True),
    ("users", "created_at", True, True),
    ("users", "last_login_at", False, False),
    ("chat_history", "id", True, True),
    ("chat_history", "job_description_id", False, False),
    ("chat_history", "role", True, False),
    ("chat_history", "content", True, False),
    ("chat_history", "created_at", True, True),
    ("ai_usage", "day", True, False),
    ("ai_usage", "bucket", True, False),
    ("ai_usage", "calls", True, True),
]


def test_columns_keep_their_required_and_default_settings():
    """Replaces the SQLite parity check for nullability and defaults: the facts were verified against the live database file, then pinned."""
    actual = {(tb, col, c["notnull"], c["default"]) for tb, info in SCH.items() for col, c in info["cols"].items()}
    assert actual == set(PINNED_COLUMNS), {"changed_or_new": sorted(actual - set(PINNED_COLUMNS)), "lost": sorted(set(PINNED_COLUMNS) - actual)}
    assert len(PINNED_COLUMNS) == 91          # the live file had 12 tables and 91 columns, all present


@pytest.mark.parametrize("banned", ["AUTOINCREMENT", "PRAGMA", "COLLATE NOCASE", "CURRENT_TIMESTAMP", "INSERT OR", r"\bBLOB\b", r"\bREAL\b"])
def test_schema_uses_only_postgres_syntax_and_types(banned):
    assert not re.search(banned, re.sub(r"--[^\n]*", "", SCHEMA) + " ".join(SCHEMA_UPGRADES), re.I), banned


def test_indexes_the_code_depends_on_exist():
    text = re.sub(r"--[^\n]*", "", SCHEMA)
    for name in ("uq_active_application", "idx_app_skills_name", "idx_chunks_app"):
        assert f"INDEX IF NOT EXISTS {name}" in text, name
    assert "(lower(skill_name))" in text                                             # case-insensitive skill lookups
