"""The Postgres schema must describe exactly the same tables as the SQLite one. Checked without a Postgres server by comparing
SQLite's own description of SCHEMA with a parse of SCHEMA_PG, so a column added to one and forgotten in the other fails here."""
import re
import sqlite3

import pytest

from app.database import PG_UPGRADES, SCHEMA, SCHEMA_PG

TYPE_MAP = {"INTEGER": "INTEGER", "REAL": "DOUBLE PRECISION", "TEXT": "TEXT", "BLOB": "BYTEA"}


def sqlite_model():
    c = sqlite3.connect(":memory:")
    c.executescript(SCHEMA)
    model = {}
    for (t,) in c.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").fetchall():
        cols = {r[1]: {"type": r[2], "notnull": bool(r[3]), "pk": bool(r[5])} for r in c.execute(f"PRAGMA table_info({t})")}
        fks = {(f[3], f[2], f[4], f[6]) for f in c.execute(f"PRAGMA foreign_key_list({t})")}      # (column, table, to, on delete)
        model[t] = {"cols": cols, "fks": fks}
    idx = {}
    for name, tbl, sql in c.execute("SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL"):
        idx[name] = {"table": tbl, "unique": "UNIQUE" in sql.upper().split("INDEX")[0], "partial": " WHERE " in sql.upper()}
    # the ai_usage table is created on first use by app/services/quota.py rather than in SCHEMA
    model["ai_usage"] = {"cols": {"day": {"type": "TEXT", "notnull": True, "pk": True}, "bucket": {"type": "TEXT", "notnull": True, "pk": True},
                                  "calls": {"type": "INTEGER", "notnull": True, "pk": False}}, "fks": set()}
    return model, idx


def pg_model():
    text = re.sub(r"--[^\n]*", "", SCHEMA_PG)
    model = {}
    for m in re.finditer(r"CREATE TABLE IF NOT EXISTS (\w+) \((.*?)\n\);", text, re.S):
        table, body = m.group(1), m.group(2)
        cols, fks, table_pk = {}, set(), []
        for line in [x.strip().rstrip(",") for x in body.split("\n") if x.strip()]:
            if line.startswith("PRIMARY KEY"):
                table_pk = [c.strip() for c in re.search(r"\((.*)\)", line).group(1).split(",")]
                continue
            name, rest = line.split(None, 1)
            type_ = re.match(r"(DOUBLE PRECISION|\w+)", rest).group(1)
            ref = re.search(r"REFERENCES (\w+)\((\w+)\)(?: ON DELETE (\w+(?: \w+)?))?", rest)
            if ref:
                fks.add((name, ref.group(1), ref.group(2), (ref.group(3) or "NO ACTION").upper()))
            cols[name] = {"type": type_, "notnull": "NOT NULL" in rest or "PRIMARY KEY" in rest, "pk": "PRIMARY KEY" in rest,
                          "identity": "GENERATED BY DEFAULT AS IDENTITY" in rest, "unique": "UNIQUE" in rest, "line": rest}
        for c in table_pk:
            cols[c]["pk"] = cols[c]["notnull"] = True
        model[table] = {"cols": cols, "fks": fks}
    idx = {}
    for m in re.finditer(r"CREATE (UNIQUE )?INDEX IF NOT EXISTS (\w+)\s+ON (\w+)\s*\((.*?)\)(\s+WHERE [^;]+)?;", text, re.S):
        idx[m.group(2)] = {"table": m.group(3), "unique": bool(m.group(1)), "partial": bool(m.group(5)), "cols": m.group(4).strip()}
    return model, idx


def test_same_tables_and_columns():
    s, _ = sqlite_model()
    p, _ = pg_model()
    assert set(s) == set(p)
    for table in s:
        assert set(s[table]["cols"]) == set(p[table]["cols"]), f"{table}: column names differ"


def test_column_types_and_nullability_map_cleanly():
    s, _ = sqlite_model()
    p, _ = pg_model()
    for table, info in s.items():
        for col, a in info["cols"].items():
            b = p[table]["cols"][col]
            assert TYPE_MAP[a["type"]] == b["type"], f"{table}.{col}: {a['type']} should become {TYPE_MAP[a['type']]}, got {b['type']}"
            if not a["pk"]:
                assert a["notnull"] == b["notnull"], f"{table}.{col}: NOT NULL differs"


def test_primary_keys_and_identity_columns():
    s, _ = sqlite_model()
    p, _ = pg_model()
    for table, info in s.items():
        assert {c for c, a in info["cols"].items() if a["pk"]} == {c for c, b in p[table]["cols"].items() if b["pk"]}, f"{table}: primary key differs"
    for table, info in p.items():
        for col, b in info["cols"].items():
            if b["pk"] and b["type"] == "INTEGER" and table != "ai_usage":
                assert b["identity"], f"{table}.{col}: integer id must be an identity column (the SQLite AUTOINCREMENT)"


def test_foreign_keys_and_cascades_match():
    s, _ = sqlite_model()
    p, _ = pg_model()
    for table in s:
        assert s[table]["fks"] == p[table]["fks"], f"{table}: foreign keys differ"
    assert all(fk[3] == "CASCADE" for t in p.values() for fk in t["fks"])


def test_indexes_match():
    _, si = sqlite_model()
    _, pi = pg_model()
    assert set(si) == set(pi)
    for name in si:
        assert (si[name]["table"], si[name]["unique"], si[name]["partial"]) == (pi[name]["table"], pi[name]["unique"], pi[name]["partial"]), name
    assert "lower(skill_name)" in pi["idx_app_skills_name"]["cols"]                  # replaces COLLATE NOCASE


def test_unique_constraints_and_checks_carried_over():
    p, _ = pg_model()
    for table, col in (("candidates", "email"), ("users", "email"), ("analysis_results", "application_id")):
        assert p[table]["cols"][col]["unique"], f"{table}.{col} must stay UNIQUE"
    assert "CHECK (role IN ('admin', 'recruiter'))" in p["users"]["cols"]["role"]["line"]


def test_defaults_carried_over():
    p, _ = pg_model()
    assert "DEFAULT 'required'" in p["job_required_skills"]["cols"]["importance"]["line"]
    assert "DEFAULT 0" in p["job_required_skills"]["cols"]["is_gate"]["line"]
    assert "DEFAULT 'active'" in p["applications"]["cols"]["application_status"]["line"]
    for table, info in p.items():
        if "created_at" in info["cols"]:
            assert "to_char(timezone('utc', now())" in info["cols"]["created_at"]["line"], table      # same text format as SQLite


@pytest.mark.parametrize("banned", ["AUTOINCREMENT", "PRAGMA", "COLLATE NOCASE", "CURRENT_TIMESTAMP", "INSERT OR", r"\bBLOB\b", r"\bREAL\b"])
def test_postgres_schema_has_no_sqlite_only_syntax(banned):
    assert not re.search(banned, re.sub(r"--[^\n]*", "", SCHEMA_PG) + " ".join(PG_UPGRADES), re.I), banned


def test_upgrade_statements_cover_every_column_added_after_the_first_release():
    p, _ = pg_model()
    for stmt in PG_UPGRADES:
        m = re.match(r"ALTER TABLE (\w+) ADD COLUMN IF NOT EXISTS (\w+) ", stmt)
        assert m and m.group(2) in p[m.group(1)]["cols"], stmt
    assert {re.match(r"ALTER TABLE \w+ ADD COLUMN IF NOT EXISTS (\w+)", x).group(1) for x in PG_UPGRADES} == {
        "session_epoch", "owner_id", "weights", "cutoffs", "is_gate"}
