"""Database schema and connection helper. The database is PostgreSQL; app/db.py holds the adapter (see docs/POSTGRES.md)."""
from app import config

# ---------------------------------------------------------------- the schema (PostgreSQL)
# Design notes:
#   * ids are identity columns (GENERATED BY DEFAULT, so rows can be loaded with their old ids)
#   * scores and years are DOUBLE PRECISION (Postgres REAL is only 4 bytes); search vectors are BYTEA
#   * dates are TEXT in 'YYYY-MM-DD HH:MM:SS' UTC, because the code and the page read and slice them as text
#   * JSON (education, scores, weights ...) is stored as TEXT and parsed in Python
#   * tests/test_schema_needs.py checks every SQL statement in app/ against this text
PG_NOW = "to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS')"

SCHEMA = """
CREATE TABLE IF NOT EXISTS candidates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT UNIQUE,
    phone TEXT,
    created_at TEXT NOT NULL DEFAULT {now}
);

CREATE TABLE IF NOT EXISTS job_descriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER,
    title TEXT,
    raw_text TEXT,
    min_experience_years DOUBLE PRECISION,
    soft_skills TEXT,
    summary TEXT,
    weights TEXT,
    cutoffs TEXT,
    created_at TEXT NOT NULL DEFAULT {now}
);

CREATE TABLE IF NOT EXISTS job_required_skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_description_id INTEGER NOT NULL REFERENCES job_descriptions(id) ON DELETE CASCADE,
    skill_name TEXT NOT NULL,
    is_gate INTEGER NOT NULL DEFAULT 0,
    importance TEXT NOT NULL DEFAULT 'required'
);

CREATE TABLE IF NOT EXISTS applications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id INTEGER NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
    job_description_id INTEGER NOT NULL REFERENCES job_descriptions(id) ON DELETE CASCADE,
    resume_filename TEXT,
    resume_hash TEXT NOT NULL,
    raw_text TEXT,
    education TEXT,
    experience_years DOUBLE PRECISION,
    experience_detail TEXT,
    internships TEXT,
    soft_skills TEXT,
    profile_json TEXT,
    projects TEXT,
    certifications TEXT,
    extraction_status TEXT NOT NULL DEFAULT 'ok',
    verification_status TEXT NOT NULL DEFAULT 'unverified',
    application_status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL DEFAULT {now}
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_active_application
    ON applications(candidate_id, job_description_id) WHERE application_status = 'active';

CREATE TABLE IF NOT EXISTS application_skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    skill_name TEXT NOT NULL,
    raw_skill TEXT,
    level TEXT
);
CREATE INDEX IF NOT EXISTS idx_app_skills_name ON application_skills (lower(skill_name));

CREATE TABLE IF NOT EXISTS resume_chunks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    text TEXT NOT NULL,
    embedding BYTEA
);
CREATE INDEX IF NOT EXISTS idx_chunks_app ON resume_chunks(application_id);

CREATE TABLE IF NOT EXISTS analysis_results (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER NOT NULL UNIQUE REFERENCES applications(id) ON DELETE CASCADE,
    job_description_id INTEGER NOT NULL REFERENCES job_descriptions(id) ON DELETE CASCADE,
    match_score DOUBLE PRECISION,
    skill_match_ratio DOUBLE PRECISION,
    component_scores TEXT,
    skill_breakdown TEXT,
    llm_status TEXT,
    matching_skills TEXT,
    missing_skills TEXT,
    strengths TEXT,
    weaknesses TEXT,
    summary TEXT,
    interview_questions TEXT,
    recommendation TEXT,
    created_at TEXT NOT NULL DEFAULT {now}
);

CREATE TABLE IF NOT EXISTS verification_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    field TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    evidence_quote TEXT,
    created_at TEXT NOT NULL DEFAULT {now}
);

CREATE TABLE IF NOT EXISTS skill_aliases (
    alias TEXT PRIMARY KEY,
    canonical TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'seed'
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'recruiter' CHECK (role IN ('admin', 'recruiter')),
    is_active INTEGER NOT NULL DEFAULT 1,
    session_epoch INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT {now},
    last_login_at TEXT
);

CREATE TABLE IF NOT EXISTS chat_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_description_id INTEGER REFERENCES job_descriptions(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT {now}
);

CREATE TABLE IF NOT EXISTS ai_usage (
    day TEXT NOT NULL,
    bucket TEXT NOT NULL,
    calls INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (day, bucket)
);
""".replace("{now}", PG_NOW)

# Brings a database created by an earlier release of this schema up to date (a no-op on a fresh one).
SCHEMA_UPGRADES = (
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS session_epoch INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS owner_id INTEGER",
    "ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS weights TEXT",
    "ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS cutoffs TEXT",
    "ALTER TABLE job_required_skills ADD COLUMN IF NOT EXISTS is_gate INTEGER NOT NULL DEFAULT 0",
)


# Starter alias map: lowercase variant -> canonical name. Grows over time.
SEED_ALIASES = {
    "ml": "Machine Learning",
    "machine learning": "Machine Learning",
    "py": "Python",
    "python3": "Python",
    "js": "JavaScript",
    "fast api": "FastAPI",
    "fastapi": "FastAPI",
    "tf": "TensorFlow",
    "tensorflow": "TensorFlow",
    "docker": "Docker",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "sklearn": "Scikit-learn",
    "scikit learn": "Scikit-learn",
    "sql": "SQL",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "opencv": "OpenCV",
    "yolo": "YOLO",
    "lstm": "LSTM",
    "cnn": "CNN",
    "cnns": "CNN",
    "llm": "LLMs",
    "llms": "LLMs",
    "large language models": "LLMs",
    "rag": "RAG",
    "retrieval-augmented generation": "RAG",
    "github": "Git/GitHub",
    "git": "Git/GitHub",
    "git/github": "Git/GitHub",
    "typescript": "TypeScript",
    "javascript": "JavaScript",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "react.js": "React",
    "power bi": "Power BI",
    "aws": "AWS",
    "k8s": "Kubernetes",
    "scikit-learn": "Scikit-learn",
}


def get_connection():
    """Open a private connection to the database named by DATABASE_URL. Rows read by name or position, like the rest of the app expects."""
    if not config.DATABASE_URL:
        raise RuntimeError("DATABASE_URL is not set. Put your PostgreSQL address in .env, e.g. DATABASE_URL=postgresql://user:password@host:5432/dbname")
    from app.db import connect_pg
    return connect_pg(config.DATABASE_URL)


def init_db() -> None:
    """Create all tables (a no-op where they exist), add columns newer releases need, and seed the skill alias table. Safe on every start."""
    conn = get_connection()
    try:
        conn.executescript(SCHEMA)
        for statement in SCHEMA_UPGRADES:
            conn.execute(statement)
        conn.executemany("INSERT INTO skill_aliases (alias, canonical) VALUES (?, ?) ON CONFLICT (alias) DO NOTHING", SEED_ALIASES.items())
        conn.commit()
    finally:
        conn.close()


if __name__ == "__main__":
    init_db()
    print("Database ready (PostgreSQL)")
