"""The starter table of skill names: every spelling people use for a skill, mapped to ONE canonical name.

How it is used: a skill from a resume or a job is lower-cased and looked up here (app/llm/skill_canonicalizer.py). A hit costs nothing;
a miss goes to the AI in one batched call and the answer is saved back into the same table (source 'ai'). So the more real spellings
live here, the fewer AI calls and the fewer "same skill, different name" misses.

ALIAS_GROUPS is written as  canonical name -> [other spellings]. The canonical name itself is added automatically. Rules the tests enforce:
  * one spelling belongs to exactly ONE canonical name (a clash stops the app from starting, so it cannot go unnoticed)
  * different technologies are never merged (Java is not JavaScript, C is not C++ or C#, React is not React Native, SQL is not MySQL ...)
  * soft skills (communication, teamwork) are not here: they are kept apart from technical skills on purpose
  * deliberately left out because they are ambiguous words: "cv" (curriculum vitae), "gtm" (Google Tag Manager or go-to-market), "pm", "be", "can", "ds"

Canonical names that already existed in real data (learned earlier by the AI, e.g. "REST API Design", "Advanced Excel", "HTML/CSS",
"CI/CD Pipelines", "Git/GitHub") are kept exactly, so scores do not change under existing jobs.
"""

ALIAS_GROUPS: dict[str, list[str]] = {
    # ------------------------------------------------------------------ programming languages
    "Python": ["py", "python3", "python 3", "python 3.x", "python programming", "python3.x", "cpython"],
    "Java": ["core java", "java se", "java 8", "java 11", "java 17", "java programming", "java development", "jdk"],
    "Java EE": ["j2ee", "jee", "jakarta ee", "java enterprise edition"],
    "JavaScript": ["js", "java script", "es6", "es6+", "ecmascript", "vanilla js", "vanilla javascript", "javascript (es6+)", "javascript es6"],
    "TypeScript": ["ts", "type script"],
    "C": ["c programming", "c language", "ansi c"],
    "C++": ["cpp", "c plus plus", "c/c++", "c++ programming", "modern c++"],
    "C#": ["csharp", "c sharp", "c# programming"],
    "Go": ["golang", "go lang", "go programming"],
    "Rust": ["rust lang", "rustlang"],
    "Ruby": ["ruby programming"],
    "Ruby on Rails": ["rails", "ror", "ruby on rail"],
    "PHP": ["php 7", "php 8", "php programming"],
    "Kotlin": ["kotlin programming"],
    "Swift": ["swift programming", "swift 5"],
    "Dart": ["dart programming", "dart lang"],
    "Scala": ["scala programming"],
    "R": ["r programming", "r language", "r studio", "rstudio"],
    "MATLAB": ["matlab programming", "mat lab"],
    "Bash/Shell Scripting": ["bash", "shell", "shell scripting", "bash scripting", "sh", "unix shell", "shell script", "shell scripts", "bash scripts", "zsh"],
    "PowerShell": ["power shell", "powershell scripting"],
    "SQL": ["structured query language", "sql queries", "sql programming", "sql basics", "basic sql", "sql query writing"],
    "PL/SQL": ["plsql", "pl sql", "oracle pl/sql"],
    "T-SQL": ["tsql", "t sql", "transact-sql", "transact sql"],
    "Perl": ["perl scripting"],
    "Objective-C": ["objective c", "objc"],
    "Assembly Language": ["assembly", "assembly programming", "x86 assembly", "arm assembly"],
    "Solidity": ["solidity programming"],
    "Julia": ["julia lang", "julia programming"],
    "Groovy": ["groovy scripting"],
    "Verilog": ["verilog hdl"],
    "VHDL": ["vhdl programming"],

    # ------------------------------------------------------------------ web front end
    "HTML/CSS": ["html", "css", "html5", "css3", "html & css", "html and css", "html5/css3", "html/css3", "html, css", "html5 & css3"],
    "React": ["react.js", "reactjs", "react js", "react 18", "react (hooks)", "react hooks"],
    "Redux": ["redux toolkit", "react redux", "redux saga", "rtk"],
    "Next.js": ["nextjs", "next js"],
    "Vue.js": ["vue", "vuejs", "vue js", "vue 3", "vue.js 3"],
    "Nuxt.js": ["nuxt", "nuxtjs", "nuxt js"],
    "Angular": ["angular 2+", "angular2", "angular 14", "angular 15", "angular cli", "angular framework"],
    "AngularJS": ["angular.js", "angular js", "angularjs 1.x"],
    "Svelte": ["sveltekit", "svelte kit"],
    "jQuery": ["jquery ui"],
    "Bootstrap": ["bootstrap 5", "bootstrap 4", "twitter bootstrap", "bootstrap css"],
    "Tailwind CSS": ["tailwind", "tailwindcss", "tailwind css 3"],
    "Sass/SCSS": ["sass", "scss", "less/sass"],
    "Material UI": ["mui", "material-ui", "material ui (mui)", "materialui"],
    "Webpack": ["webpack 5", "module bundlers"],
    "Vite": ["vitejs", "vite.js"],
    "npm/Yarn": ["npm", "yarn", "pnpm", "npm/yarn", "node package manager"],
    "Responsive Web Design": ["responsive design", "responsive web design (rwd)", "mobile-first design", "mobile first design", "responsive layouts", "responsive ui"],
    "Web Accessibility": ["accessibility", "wcag", "a11y", "wcag 2.1", "web accessibility (wcag)"],
    "Progressive Web Apps": ["pwa", "pwas", "progressive web app"],
    "AJAX": ["ajax requests", "xhr"],
    "Web Development": ["web dev", "web development (front end)", "website development", "web application development"],
    "Full-Stack Development": ["full stack", "full-stack", "fullstack", "full stack development", "full-stack development", "full stack web development", "mern", "mern stack", "mean stack"],
    "Frontend Development": ["frontend", "front end", "front-end", "front end development", "front-end development", "frontend development", "front end developer skills"],

    # ------------------------------------------------------------------ back end
    "Node.js": ["node", "nodejs", "node js", "node.js backend"],
    "Express.js": ["express", "expressjs", "express js", "express.js framework"],
    "NestJS": ["nest", "nestjs", "nest.js", "nest js"],
    "Django": ["django framework", "django 4", "django orm"],
    "Django REST Framework": ["drf", "django rest", "django-rest-framework", "django rest framework (drf)"],
    "Flask": ["flask framework", "flask api", "flask-restful"],
    "FastAPI": ["fast api", "fast-api"],
    "Spring Boot": ["springboot", "spring-boot", "spring boot 3", "spring boot framework"],
    "Spring": ["spring framework", "spring mvc", "spring core", "spring security", "spring cloud"],
    "Hibernate/JPA": ["hibernate", "jpa", "spring data jpa", "hibernate orm", "java persistence api"],
    ".NET": ["dotnet", ".net core", ".net framework", "dot net", ".net 6", ".net 8"],
    "ASP.NET": ["asp.net core", "asp.net mvc", "asp net", "aspnet", "asp.net web api"],
    "Laravel": ["laravel framework", "laravel php"],
    "GraphQL": ["graph ql", "graphql api", "apollo graphql", "apollo server"],
    "gRPC": ["grpc", "protocol buffers", "protobuf"],
    "REST API Design": ["rest api", "rest apis", "restful api", "restful apis", "restful", "rest", "api development", "api design", "rest api development",
                        "restful web services", "restful services", "rest services", "web apis", "api integration", "rest api design & integration",
                        "rest api integration", "restful api development", "building apis", "api building"],
    "API Testing": ["api automation", "rest api testing", "api test automation", "rest api integration and testing", "testing apis", "api testing (postman)", "response validation", "status code validation", "json validation", "postman-style request/response debugging", "request/response validation", "api validation"],
    "API Documentation": ["api docs", "api documentation and walkthroughs", "documenting apis"],
    "OpenAPI/Swagger": ["openapi", "swagger", "swagger ui", "openapi specification", "swagger/openapi", "open api"],
    "WebSockets": ["websocket", "web sockets", "socket.io", "socketio", "real-time communication"],
    "Microservices Architecture": ["microservices", "microservice", "microservice architecture", "microservices architecture (basics)", "modular service design",
                                   "service-oriented architecture", "soa"],
    "Message Queues": ["message queue", "message broker", "message brokers", "mq", "async messaging", "event-driven architecture", "event driven architecture"],
    "RabbitMQ": ["rabbit mq", "rabbitmq (amqp)"],
    "Kafka": ["apache kafka", "kafka streams", "kafka (basics)"],
    "Celery": ["celery workers", "celery task queue", "celery beat"],
    "JWT": ["json web token", "json web tokens", "jwt authentication", "jwt tokens"],
    "OAuth": ["oauth2", "oauth 2.0", "oauth2.0", "oauth 2", "openid connect", "oidc"],
    "Authentication & Authorization": ["authentication", "authorization", "authn", "authz", "authentication and authorization", "auth", "user authentication"],
    "RBAC": ["role-based access control", "role based access control", "role-based access"],
    "API Gateway": ["api gateways", "aws api gateway", "kong", "kong gateway"],
    "Caching": ["cache", "caching strategies", "distributed caching", "cache invalidation"],
    "Object-Oriented Programming": ["oop", "oops", "oops concepts", "object oriented programming", "object-oriented", "object oriented", "oop concepts",
                                    "oop principles", "object oriented design", "object-oriented design", "ood", "object-oriented programming (oop)"],
    "Design Patterns": ["software design patterns", "gof design patterns"],
    "Data Structures": ["data structure", "data structures basics"],
    "Algorithms": ["algorithm", "algorithm design", "algorithms and complexity", "problem solving algorithms"],
    "Data Structures and Algorithms": ["dsa", "data structures & algorithms", "data structures and algorithms", "data structures & algorithm", "dsa (data structures and algorithms)"],
    "Multithreading": ["multi-threading", "multi threading", "concurrency", "concurrent programming", "threading", "multithreaded programming", "parallel programming"],
    "Exception Handling": ["error handling", "exception management", "exceptions handling", "try catch", "error and exception handling"],
    "Collections": ["java collections", "collections framework", "java collections framework", "jcf"],
    "Debugging": ["debug", "bug fixing", "bug fixes", "code debugging", "debugging skills", "debugging and troubleshooting", "bug fix"],
    "Troubleshooting": ["problem troubleshooting", "technical troubleshooting", "issue troubleshooting", "technical support troubleshooting"],
    "Code Reviews": ["code review", "peer code review", "pull request reviews", "pr reviews", "peer reviews"],
    "Technical Documentation": ["technical writing", "technical docs", "software documentation", "documentation", "documenting code", "technical content writing", "documentation writing", "user manuals", "api documentation writing", "knowledge base articles"],
    "SDLC": ["software development life cycle", "software development lifecycle (sdlc)", "software development lifecycle", "software development life cycle (sdlc)", "software development process", "sdlc models"],
    "Linux": ["unix", "linux/unix", "unix/linux", "linux administration", "linux admin", "ubuntu", "centos", "rhel", "red hat", "red hat linux", "debian", "linux os",
              "linux commands", "unix/linux administration"],

    # ------------------------------------------------------------------ databases and data stores
    "PostgreSQL": ["postgres", "postgre sql", "psql", "postgresql 14", "postgresql 15", "postgres db", "postgre"],
    "MySQL": ["my sql", "mysql 8", "mysql database", "mysql workbench"],
    "SQLite": ["sqlite3", "sqlite database"],
    "MongoDB": ["mongo", "mongo db", "mongodb atlas", "mongoose"],
    "Redis": ["redis cache", "redis db", "redis (caching)"],
    "Cassandra": ["apache cassandra", "cassandra db", "cassandra database"],
    "DynamoDB": ["dynamo db", "amazon dynamodb", "aws dynamodb"],
    "Elasticsearch": ["elastic search", "elastic", "elasticsearch (elk)"],
    "ELK Stack": ["elk", "elastic stack", "elk stack (elasticsearch, logstash, kibana)", "logstash", "kibana"],
    "Oracle Database": ["oracle", "oracle db", "oracle sql", "oracle 19c", "oracle database 19c"],
    "SQL Server": ["ms sql", "mssql", "microsoft sql server", "ms sql server", "sql server 2019", "ssms"],
    "MariaDB": ["maria db"],
    "Neo4j": ["neo4j graph database"],
    "Firebase": ["firebase realtime database", "google firebase"],
    "Supabase": ["supabase db"],
    "Database Design": ["database schema design", "schema design", "db design", "database modeling", "database modelling", "database design and normalization", "er diagrams",
                        "erd", "entity relationship diagrams", "database normalization"],
    "Data Modeling": ["data modelling", "dimensional modeling", "dimensional modelling", "star schema", "data models"],
    "Query Optimization": ["sql optimization", "query tuning", "sql tuning", "database performance tuning", "query performance", "sql performance tuning",
                           "indexing", "database indexing"],
    "ORM": ["orm frameworks", "object relational mapping", "object-relational mapping", "sqlalchemy orm"],
    "SQLAlchemy": ["sql alchemy", "sqlalchemy core"],
    "Prisma": ["prisma orm"],
    "Sequelize": ["sequelize orm"],
    "Stored Procedures": ["stored procedure", "stored procs", "sql stored procedures", "triggers and stored procedures"],
    "NoSQL": ["nosql databases", "no sql", "nosql database", "non-relational databases"],
    "Data Warehousing": ["data warehouse", "dwh", "data warehouses", "data warehouse design", "enterprise data warehouse", "edw"],
    "Snowflake": ["snowflake data warehouse", "snowflake db", "snowflake cloud"],
    "BigQuery": ["big query", "google bigquery", "gcp bigquery"],
    "Amazon Redshift": ["redshift", "aws redshift", "amazon redshift spectrum"],
    "Databricks": ["databricks lakehouse", "azure databricks", "delta lake"],
    "dbt": ["data build tool", "dbt core", "dbt cloud"],
    "Apache Spark": ["spark", "apache spark (pyspark)", "spark sql", "spark streaming"],
    "PySpark": ["py spark", "spark with python"],
    "Hadoop": ["apache hadoop", "hdfs", "mapreduce", "hadoop ecosystem", "big data hadoop"],
    "Apache Hive": ["hive", "hiveql", "hive sql"],
    "Apache Airflow": ["airflow", "airflow dags", "apache airflow (dags)"],
    "Data Pipelines": ["data pipeline", "etl", "elt", "etl/elt", "etl/elt pipeline", "etl pipelines", "etl processes", "data ingestion", "etl development",
                       "etl tools", "elt pipelines", "pipeline development", "etl/elt fundamentals", "etl/elt basics"],
    "Big Data": ["big data technologies", "big data analytics", "big data processing"],
    "Data Engineering": ["data engineer skills", "data platform engineering", "analytics engineering"],
    "Data Governance": [],

    # ------------------------------------------------------------------ DevOps, cloud, systems
    "Docker": ["docker containers", "docker container", "docker engine", "dockerfile", "dockerfiles", "docker images", "docker (basics)"],
    "Docker Compose": ["docker-compose", "docker compose v2", "compose files"],
    "Containerization": ["containerisation", "containers", "container technologies", "container platforms"],
    "Kubernetes": ["k8s", "kube", "kubernetes (k8s)", "kubernetes orchestration", "container orchestration", "kubectl", "k3s", "minikube"],
    "Helm": ["helm charts", "helm chart", "helm 3"],
    "Jenkins": ["jenkins ci", "jenkins pipeline", "jenkins pipelines", "jenkinsfile", "jenkins ci/cd"],
    "GitHub Actions": ["github action", "gh actions", "github actions ci/cd", "github ci/cd", "github workflows"],
    "GitLab CI": ["gitlab ci/cd", "gitlab-ci", "gitlab ci/cd pipelines", "gitlab pipelines", "gitlab runner"],
    "CircleCI": ["circle ci", "circleci pipelines"],
    "Azure DevOps": ["azure devops services", "azure pipelines", "vsts", "tfs"],
    "ArgoCD": ["argo cd", "argocd gitops", "argo workflows"],
    "GitOps": ["git ops", "gitops workflows", "fluxcd"],
    "CI/CD Pipelines": ["ci/cd", "cicd", "ci cd", "ci-cd", "continuous integration", "continuous delivery", "continuous deployment", "ci/cd pipeline", "ci/cd tools",
                        "continuous integration/continuous deployment", "continuous integration and continuous delivery", "ci/cd (jenkins)", "pipeline automation",
                        "build pipelines", "build and deployment pipelines"],
    "Terraform": ["hashicorp terraform", "terraform (iac)", "terraform cloud", "terraform modules", "tf (terraform)"],
    "Ansible": ["ansible playbooks", "ansible automation", "red hat ansible"],
    "Chef": ["chef automation", "chef cookbooks"],
    "Puppet": ["puppet automation", "puppet manifests"],
    "Infrastructure as Code": ["iac", "infrastructure-as-code", "infra as code", "infrastructure automation", "iac tools"],
    "CloudFormation": ["aws cloudformation", "cloud formation", "cfn"],
    "Git/GitHub": ["github", "git", "git/github", "git & github", "git and github", "git hub", "git version control", "github (version control)", "git (version control)"],
    "GitLab": ["gitlab repositories", "gitlab.com"],
    "Bitbucket": ["bit bucket", "atlassian bitbucket"],
    "Version Control": ["vcs", "source control", "source code management", "scm tools", "version control systems", "version control (git)", "revision control"],
    "Nginx": ["nginx server", "nginx reverse proxy", "reverse proxy"],
    "Apache HTTP Server": ["apache", "apache httpd", "apache http server", "apache web server", "apache2"],
    "Load Balancing": ["load balancer", "load balancers", "load-balancing", "haproxy", "elb"],
    "Prometheus": ["prometheus monitoring", "promql", "prometheus (monitoring)"],
    "Grafana": ["grafana dashboards", "grafana loki"],
    "Datadog": ["datadog monitoring", "datadog apm"],
    "New Relic": ["newrelic", "new relic apm"],
    "Splunk": ["splunk enterprise", "splunk siem", "splunk logs"],
    "Monitoring & Logging": ["monitoring", "logging", "observability", "monitoring and logging", "monitoring and alerting", "monitoring & alerting", "log management",
                             "application monitoring", "system monitoring", "alerting", "log analysis"],
    "Networking": ["computer networks", "computer networking", "networking fundamentals", "tcp/ip", "tcp ip", "dns", "http/https", "network protocols",
                   "osi model", "routing and switching", "lan/wan", "networking basics", "dhcp", "vpn"],
    "Site Reliability Engineering": ["sre", "site reliability", "reliability engineering", "slo/sli", "incident management"],
    "AWS": ["amazon web services", "amazon aws", "aws cloud", "aws services", "aws (ec2, s3)", "amazon web services (aws)"],
    "EC2": ["amazon ec2", "aws ec2", "ec2 instances", "elastic compute cloud"],
    "S3": ["amazon s3", "aws s3", "s3 buckets", "amazon simple storage service"],
    "Lambda": ["aws lambda", "lambda functions", "aws lambda functions"],
    "RDS": ["amazon rds", "aws rds", "rds (aws)"],
    "AWS IAM": ["iam roles", "aws identity and access management"],
    "VPC": ["aws vpc", "amazon vpc", "virtual private cloud"],
    "CloudWatch": ["aws cloudwatch", "amazon cloudwatch"],
    "Azure": ["microsoft azure", "ms azure", "azure cloud", "azure services", "azure (basics)"],
    "Google Cloud Platform": ["gcp", "google cloud", "google cloud platform (gcp)", "gcp services", "google cloud services"],
    "Serverless": ["serverless computing", "serverless architecture", "serverless framework", "faas", "cloud functions"],
    "Cloud Computing": ["cloud", "cloud platforms", "cloud technologies", "cloud services", "cloud infrastructure", "public cloud", "cloud fundamentals", "cloud basics"],
    "Virtualization": ["virtual machines", "vm"],
    "System Administration": ["sysadmin", "sys admin", "system admin", "systems administration", "server administration", "it administration"],

    # ------------------------------------------------------------------ AI, ML and data science
    "Machine Learning": ["ml", "machine-learning", "machine learning fundamentals", "ml algorithms", "machine learning algorithms", "machine learning models", "ml models",
                         "applied machine learning", "supervised learning", "unsupervised learning", "classical ml"],
    "Deep Learning": ["dl", "deep-learning", "deep learning models", "dnn", "deep neural networks"],
    "Neural Networks": ["neural network", "neural nets", "ann", "artificial neural networks", "artificial neural network", "neural networks (ann)"],
    "Computer Vision": ["computervision", "computer-vision", "machine vision", "computer vision (cv)", "cv algorithms", "visual recognition", "vision models", "computer vision models"],
    "Image Processing": ["image analysis", "digital image processing", "image preprocessing", "image augmentation"],
    "Object Detection": ["object detection models", "object recognition", "detection models", "bounding box detection"],
    "Natural Language Processing": ["nlp", "natural language understanding", "nlu", "natural language processing (nlp)", "text processing", "text mining", "text analytics",
                                    "nlp techniques", "language processing"],
    "Artificial Intelligence": ["ai", "artificial intelligence (ai)", "ai/ml", "ai and machine learning", "ai & ml", "ml/ai", "applied ai"],
    "Generative AI": ["gen ai", "genai", "gen-ai", "generative artificial intelligence", "generative ai (genai)", "generative models", "genai applications", "gen ai applications"],
    "LLMs": ["llm", "large language models", "large language model", "large language models (llms)", "llm applications", "llm-based applications", "foundation models"],
    "Prompt Engineering": ["prompt design", "prompting", "prompt design and evaluation", "prompt optimization", "prompt writing", "prompt engineering techniques", "prompt/context engineering", "context engineering", "prompt and context engineering"],
    "RAG": ["retrieval-augmented generation", "retrieval augmented generation", "rag (retrieval-augmented generation)", "rag pipelines", "rag systems", "rag architecture", "retrieval-augmented generation (rag)", "retrieval augmented generation (rag)"],
    "Vector Databases": ["vector database", "vector db", "vector dbs", "vector stores", "vector store"],
    "Embeddings": ["text embeddings", "embedding models", "sentence embeddings", "word embeddings", "embedding"],
    "Pinecone": ["pinecone db", "pinecone vector db"],
    "ChromaDB": ["chroma", "chroma db", "chromadb vector store"],
    "FAISS": ["faiss index", "facebook ai similarity search"],
    "Hugging Face": ["huggingface", "hf", "hugging face hub", "huggingface hub", "hf models"],
    "Transformers": ["transformer models", "huggingface transformers", "transformer architecture", "transformers library", "attention mechanism"],
    "BERT": ["bert model", "bert embeddings", "distilbert", "roberta"],
    "LangChain": ["lang chain", "langchain framework", "langchain agents"],
    "LangGraph": ["lang graph", "langgraph agents"],
    "LlamaIndex": ["llama index", "llama-index", "gpt index"],
    "OpenAI API": ["openai", "open ai", "open ai api", "gpt api", "gpt-4 api", "openai gpt", "openai apis", "chatgpt api", "openai sdk"],
    "Gemini API": ["gemini", "google gemini", "gemini 2.5 flash api", "gemini pro", "google gemini api", "gemini flash"],
    "Groq API": ["groq", "groq cloud", "groq inference"],
    "Ollama": ["ollama local llm", "local llms", "local llm"],
    "Agentic Architecture": ["agentic query routing", "llm-based agents & agentic pipelines", "ai agents", "agentic ai", "multi-agent systems",
                             "llm agents", "agentic workflows", "autonomous agents", "agentic systems"],
    "Function Calling": ["function/tool calling", "llm tool/function calling", "tool calling", "tool use", "llm tool use"],
    "Fine-Tuning": ["fine tuning", "finetuning", "llm fine-tuning", "model fine-tuning", "peft", "qlora", "instruction tuning"],
    "PyTorch": ["torch", "py torch", "pytorch lightning", "pytorch (deep learning)"],
    "TensorFlow": ["tf", "tensor flow", "tf2", "tensorflow 2", "tensorflow 2.x", "tensorflow/keras"],
    "Keras": ["keras api", "tf.keras", "keras (tensorflow)"],
    "Scikit-learn": ["sklearn", "scikit learn", "scikitlearn", "scikit_learn", "sk-learn", "scikit-learn (sklearn)"],
    "XGBoost": ["xgb", "xgboost classifier"],
    "LightGBM": ["light gbm", "lgbm"],
    "Pandas": ["pandas library", "python pandas", "pandas dataframe", "pandas (python)"],
    "NumPy": ["numpy arrays", "python numpy", "numerical python"],
    "SciPy": ["scipy library", "scipy stats"],
    "Matplotlib": ["matplotlib.pyplot", "pyplot", "python matplotlib"],
    "Seaborn": ["seaborn library"],
    "Plotly": ["plotly dash", "plotly express"],
    "OpenCV": ["opencv-python", "cv2", "open cv", "opencv library", "opencv (python)"],
    "YOLO": ["yolov5", "yolov8", "yolov3", "yolo v8", "yolo v5", "yolov7", "yolov4", "ultralytics", "you only look once"],
    "CNN": ["cnns", "convolutional neural networks", "convolutional neural network", "convolutional networks", "convnets"],
    "RNN": ["rnns", "recurrent neural networks", "recurrent neural network"],
    "LSTM": ["lstms", "long short-term memory", "long short term memory", "lstm networks"],
    "GAN": ["gans", "generative adversarial networks", "generative adversarial network"],
    "Reinforcement Learning": ["rl algorithms", "deep reinforcement learning", "q-learning", "drl"],
    "Time Series Analysis": ["time series", "time-series", "time series forecasting", "time-series analysis", "forecasting models", "arima", "time series modeling"],
    "Anomaly Detection": ["anomaly detection models", "outlier detection"],
    "Recommender Systems": ["recommendation systems", "recommendation engine", "recommender system", "recommendation engines", "collaborative filtering"],
    "Feature Engineering": ["feature extraction", "feature selection", "feature engineering techniques", "feature creation"],
    "Model Training": ["training models", "model training and tuning", "training machine learning models", "model building"],
    "Model Evaluation": ["model validation", "evaluating models", "model performance evaluation", "cross-validation", "cross validation", "model testing", "model evaluation & metrics", "evaluation metrics", "precision and recall", "f1 score", "confusion matrix", "roc auc"],
    "Model Deployment": ["deploying models", "ml deployment", "model serving", "deployment of ml models", "deploying machine learning models", "model deployment (streamlit)",
                         "ml model deployment"],
    "MLOps": ["ml ops", "ml operations", "machine learning operations", "ml pipelines", "ml pipeline"],
    "MLflow": ["ml flow", "mlflow tracking"],
    "Streamlit": ["streamlit apps", "streamlit dashboards", "streamlit app development"],
    "Gradio": ["gradio apps", "gradio ui"],
    "Jupyter": ["jupyter notebook", "jupyter notebooks", "jupyterlab", "jupyter lab", "ipython", "google colab", "colab", "jupyter/google colab", "kaggle notebooks"],
    "Statistics": ["statistical analysis", "applied statistics", "statistical modeling", "statistical modelling", "descriptive statistics", "inferential statistics",
                   "statistics and probability", "statistical methods", "biostatistics"],
    "Probability": ["probability theory", "probability and statistics", "probability distributions"],
    "Linear Algebra": ["linear algebra for ml", "matrix algebra", "matrices"],
    "Calculus": ["multivariable calculus", "differential calculus"],
    "Hypothesis Testing": ["statistical testing", "significance testing", "t-test", "t tests", "anova", "chi-square test", "p-values"],
    "Exploratory Data Analysis (EDA)": ["eda", "exploratory data analysis", "exploratory analysis", "data exploration"],
    "Data Cleaning": ["data cleaning & preprocessing", "data preprocessing", "data wrangling", "data cleansing", "data preparation", "data pre-processing", "data munging",
                      "data cleaning and preparation", "data transformation"],
    "Data Mining": ["data mining techniques", "knowledge discovery"],
    "Predictive Modeling": ["predictive modelling", "predictive analytics", "predictive models", "predictive modeling techniques", "forecast modeling"],
    "Data Science": ["data science fundamentals", "applied data science", "data scientist skills"],
    "Data Analysis": ["data analytics", "data analysis & visualisation", "analytical analysis", "analyzing data", "data analyses", "data analysis techniques", "business data analysis"],
    "Data Visualization": ["visualisation", "data visualisation", "visualization", "data viz", "dataviz", "charts and graphs", "data storytelling", "data visualization tools"],
    "Dashboards": ["dashboard", "dashboard development", "dashboarding", "dashboard design", "dashboard creation", "interactive dashboards", "bi dashboards",
                   "executive dashboards"],

    # ------------------------------------------------------------------ analytics and BI tools
    "Power BI": ["powerbi", "power-bi", "microsoft power bi", "ms power bi", "power bi desktop", "power bi service", "power bi (dax)"],
    "DAX": ["dax formulas", "dax queries", "dax (data analysis expressions)", "data analysis expressions"],
    "Power Query": ["power query editor", "power query (m)", "m language", "powerquery"],
    "Tableau": ["tableau desktop", "tableau public", "tableau server", "tableau dashboards"],
    "Looker": ["lookml", "looker (google)"],
    "Qlik": ["qlikview", "qlik sense", "qlik view"],
    "Advanced Excel": ["excel", "ms excel", "microsoft excel", "excel (advanced)", "excel formulas", "vlookup", "xlookup", "pivot tables", "pivot table", "excel pivot tables",
                       "excel (pivot tables, xlookup)", "excel functions", "spreadsheets", "ms-excel", "advanced excel (vlookup, pivot tables)"],
    "Google Sheets": ["gsheets", "g sheets", "google spreadsheets", "google sheet"],
    "SPSS": ["ibm spss", "spss statistics"],
    "SAS": ["sas programming", "sas analytics", "sas base"],
    "Alteryx": ["alteryx designer", "alteryx workflows"],
    "KPI reporting": ["kpi", "kpis", "kpi tracking", "reporting", "metrics reporting", "kpi dashboards", "performance reporting", "reporting & analytics", "mis reporting",
                      "mis", "management reporting", "business reporting", "report generation"],
    "A/B Testing": ["ab testing", "a/b tests", "split testing", "a b testing", "experimentation", "a/b testing & experimentation", "a/b test", "experiment design",
                    "multivariate testing", "growth experiments"],
    "Funnel Analysis": ["conversion funnel analysis", "funnel optimization", "conversion funnel", "funnel metrics", "conversion rate optimization"],
    "Cohort Analysis": ["cohort analyses", "retention analysis", "retention cohorts", "user retention analysis", "churn analysis"],
    "Google Analytics": ["ga4", "universal analytics", "google analytics 4", "google analytics (ga4)", "web analytics"],
    "Mixpanel": ["mixpanel analytics"],
    "Amplitude": ["amplitude analytics"],
    "Product Analytics": ["product metrics", "product analysis", "product data analysis", "usage analytics", "user behavior analytics", "product insights", "heap analytics"],
    "Business Intelligence": ["bi", "business intelligence (bi)", "bi tools", "bi reporting", "bi development", "business analytics"],

    # ------------------------------------------------------------------ product management
    "Product Management": ["product mgmt", "product management fundamentals", "product ownership", "product owner skills"],
    "Product Roadmap": ["roadmap", "roadmapping", "roadmap planning", "product roadmapping", "product roadmaps", "roadmaps", "roadmap management", "feature roadmap",
                        "strategic roadmap"],
    "User Stories": ["user story", "user story writing", "writing user stories", "user stories and acceptance criteria", "story writing", "user story mapping", "epics and stories"],
    "Acceptance Criteria": ["acceptance criteria definition", "defining acceptance criteria", "definition of done"],
    "Product Requirements Document": ["prd", "prds", "product requirement document", "product requirements documents", "product requirements", "prd writing",
                                      "requirements documents", "functional specifications", "functional spec", "brd", "business requirements document", "srs",
                                      "software requirements specification"],
    "Requirements Gathering": ["requirement gathering", "requirements elicitation", "requirements analysis", "business requirements", "gathering requirements", "requirement analysis",
                               "requirements management", "requirements definition", "requirements documentation", "business requirement analysis"],
    "Backlog Management": ["backlog", "product backlog", "backlog grooming", "backlog refinement", "backlog prioritization", "backlog prioritisation", "managing backlog",
                           "sprint backlog"],
    "Sprint Planning": ["sprint", "sprints", "sprint management", "sprint planning and execution", "sprint execution", "sprint reviews", "sprint retrospectives", "retrospectives"],
    "Prioritization Frameworks": ["prioritization", "prioritisation", "rice", "moscow", "rice framework", "moscow prioritization", "feature prioritization", "rice scoring",
                                  "kano model", "impact/effort matrix", "prioritization techniques", "ice scoring"],
    "Agile Methodology": ["agile", "agile/scrum", "agile methodologies", "agile development", "agile software development", "agile practices", "agile framework",
                          "agile project management", "agile and scrum", "scrum/agile", "agile (scrum)"],
    "Scrum": ["scrum methodology", "scrum framework", "scrum master", "scrum ceremonies", "scrum events", "psm"],
    "Kanban": ["kanban boards", "kanban methodology", "kanban board", "lean kanban"],
    "SAFe": ["scaled agile", "scaled agile framework", "safe agile"],
    "Waterfall": ["waterfall methodology", "waterfall model"],
    "Jira": ["atlassian jira", "jira software", "jira administration", "jira boards", "jira tickets", "jira (agile)", "jira service management", "ticketing systems",
             "ticketing tools"],
    "Confluence": ["atlassian confluence", "confluence documentation", "confluence wiki"],
    "Trello": ["trello boards"],
    "Asana": ["asana project management", "asana tasks"],
    "Notion": ["notion workspace", "notion docs", "notion.so"],
    "ClickUp": ["click up"],
    "Monday.com": ["monday com", "monday.com boards"],
    "Slack": ["slack workspace", "slack integrations"],
    "Figma": ["figma design", "figma prototyping", "figjam", "figma/sketch", "figma (ui design)", "figma designs"],
    "Wireframing": ["wireframes", "wireframe", "low-fidelity wireframes", "low fidelity wireframes", "wireframing & prototyping", "wireframing and prototyping", "mockups",
                    "mock-ups", "ui mockups"],
    "Prototyping": ["prototype", "rapid prototyping", "interactive prototypes", "high-fidelity prototypes", "clickable prototypes", "design prototyping"],
    "User Research": ["ux research", "customer research", "user interviews", "user interview", "usability research", "user research and testing", "user insights",
                      "qualitative research", "user surveys", "customer insights"],
    "Usability Testing": ["user testing", "usability studies", "usability evaluation", "usability test"],
    "Market Research": ["market analysis", "market study", "market sizing", "market research and analysis", "industry research", "market intelligence", "market trends analysis",
                        "marketing research"],
    "Competitive Analysis": ["competitor analysis", "competitive research", "competitive benchmarking", "competitive landscape analysis", "competitive intelligence",
                             "competitor benchmarking", "competitor research"],
    "Customer Discovery": ["customer development", "customer interviews", "problem discovery", "product discovery", "discovery research", "voice of customer", "voc"],
    "Go-to-Market Strategy": ["go-to-market", "go to market", "go-to-market strategy", "gtm strategy", "product launch", "product launches", "launch planning", "market launch", "gtm planning"],
    "Product Strategy": ["product vision", "product vision and strategy", "product positioning", "product thinking"],
    "Stakeholder Management": ["stakeholder communication", "stakeholder engagement", "stakeholder alignment", "managing stakeholders", "stakeholder coordination"],
    "OKRs": ["okr", "objectives and key results", "okr setting", "okr framework", "goal setting frameworks"],
    "MVP Development": ["mvp", "minimum viable product", "mvp planning", "mvp scoping", "lean startup"],
    "Project Management": ["project planning", "project coordination", "project management methodologies", "project tracking", "pmp", "project scheduling", "program management",
                           "project delivery", "project execution", "project management (pmp)"],
    "Risk Management": ["risk assessment", "risk analysis", "risk mitigation", "risk identification", "enterprise risk management"],
    "Pricing Strategy": ["pricing", "pricing analysis", "pricing models", "monetization strategy", "monetisation", "monetization"],
    "Business Analysis": ["business analyst skills", "business process analysis", "business process improvement", "business process modeling", "business process management", "bpm",
                          "gap analysis", "requirements and process analysis"],
    "Process Mapping": ["process flow", "process flows", "bpmn", "flowcharts", "process modeling", "process modelling", "workflow mapping", "process documentation", "swimlane diagrams"],
    "UML": ["uml diagrams", "unified modeling language", "use case diagrams", "class diagrams", "sequence diagrams", "use cases", "use case modeling"],
    "SWOT Analysis": ["swot", "swot analyses"],
    "Data-Driven Decision Making": ["data-driven", "data driven decisions", "data driven decision making", "data-driven decisions", "analytical decision making",
                                    "metrics-driven", "evidence-based decision making"],
    "Customer Journey Mapping": ["journey mapping", "user journey mapping", "user journeys", "customer journey", "customer journeys", "user flows", "user flow design",
                                 "experience mapping", "service blueprints"],
    "Growth Marketing": ["growth hacking", "growth strategy", "user acquisition", "acquisition marketing", "growth marketing strategy", "customer acquisition", "retention marketing"],
    "Customer Feedback Analysis": ["customer feedback", "feedback analysis", "nps", "net promoter score", "csat", "survey analysis", "voice of the customer analysis"],

    # ------------------------------------------------------------------ design
    "UI/UX Design": ["ui/ux", "ux/ui", "ui ux", "uiux", "ui design", "ux design", "user experience design", "user interface design", "user experience", "ux", "ui", "ui/ux designing",
                     "product design", "interaction design", "ux/ui design", "user experience (ux)", "ui/ux principles"],
    "Adobe XD": ["xd", "adobe xd design", "adobe experience design"],
    "Sketch": ["sketch app", "sketch design", "sketch (ui design)"],
    "Photoshop": ["adobe photoshop", "photoshop cc", "adobe photoshop cc"],
    "Illustrator": ["adobe illustrator", "illustrator cc", "vector graphics", "adobe illustrator cc"],
    "InDesign": ["adobe indesign", "indesign cc"],
    "Canva": ["canva design", "canva pro", "canva graphics"],
    "Adobe Premiere Pro": ["premiere pro", "adobe premiere", "premiere", "adobe premiere pro cc"],
    "After Effects": ["adobe after effects", "after effects motion graphics"],
    "Design Systems": ["design system", "design system management", "component libraries", "ui component library", "design tokens", "style guides"],
    "Visual Design": ["visual communication", "visual design principles", "branding design", "layout design"],
    "Typography": ["font pairing", "type design"],

    # ------------------------------------------------------------------ testing and QA
    "Manual Testing": ["manual qa", "manual test execution", "manual testing (functional)", "exploratory testing", "black box testing", "black-box testing"],
    "Automated Testing": ["automation testing", "test automation", "automated tests", "automation tests", "qa automation", "automated test", "test automation frameworks",
                          "automation qa", "automated testing frameworks"],
    "Automation Framework": ["automation framework basics", "test framework", "test automation framework", "framework design", "hybrid framework", "page object model", "pom", "page object model (pom)"],
    "Software Testing": ["testing", "qa", "quality assurance", "qa testing", "software testing (qa)", "software quality assurance", "sqa", "software testing basics",
                         "quality assurance testing", "qa engineering"],
    "Selenium": ["selenium webdriver", "selenium web driver", "selenium ide", "selenium grid", "selenium (java)", "selenium with python", "selenium automation"],
    "Cypress": ["cypress.io", "cypress testing", "cypress e2e"],
    "Playwright": ["playwright testing", "microsoft playwright", "playwright e2e"],
    "Appium": ["appium mobile testing", "appium automation"],
    "Postman": ["postman api", "postman collections", "postman (api testing)", "newman"],
    "REST Assured": ["restassured", "rest-assured", "rest assured api testing"],
    "JMeter": ["apache jmeter", "jmeter load testing", "j meter"],
    "Performance Testing": ["load testing", "stress testing", "performance and load testing", "load and performance testing", "performance test"],
    "Regression Testing": ["regression tests", "regression test", "regression suites", "regression test suites"],
    "Smoke & Sanity Testing": ["smoke testing", "sanity testing", "smoke tests", "sanity tests", "smoke and sanity testing"],
    "Test Cases": ["test case design", "test case writing", "writing test cases", "test case creation", "test cases design", "test case preparation", "test case development",
                   "test scenarios", "test case management"],
    "Test Plans": ["test plan", "test planning", "test strategy", "test plan creation", "test planning and execution", "test management"],
    "Bug Tracking": ["defect tracking", "bug reporting", "defect management", "issue tracking", "bug tracking tools", "defect reporting", "bug triage", "defect life cycle",
                     "bug life cycle"],
    "STLC": ["software testing life cycle", "software testing life cycle (stlc)", "testing life cycle"],
    "BDD": ["behavior driven development", "behaviour driven development", "behavior-driven development", "gherkin", "bdd framework"],
    "Cucumber": ["cucumber bdd", "cucumber framework", "cucumber (bdd)"],
    "TestNG": ["test ng", "testng framework"],
    "JUnit": ["junit 5", "junit5", "junit 4", "junit testing"],
    "Mockito": ["mockito framework", "mockito mocking"],
    "Pytest": ["py.test", "pytest framework", "python pytest", "pytest fixtures"],
    "Unit Testing": ["unit tests", "unit test", "unit-testing", "unit testing (junit)", "writing unit tests", "unit testing frameworks"],
    "Integration Testing": ["integration tests", "integration test", "integration testing (api)", "system integration testing"],
    "End-to-End Testing": ["e2e testing", "e2e", "end to end testing", "e2e tests", "end-to-end tests"],
    "Test-Driven Development": ["tdd", "test driven development", "test-driven development (tdd)"],
    "User Acceptance Testing": ["uat", "uat testing", "user acceptance testing (uat)", "acceptance testing"],
    "Mobile Testing": ["mobile app testing", "android testing", "ios testing", "mobile application testing", "mobile qa"],
    "Cross-Browser Testing": ["browser compatibility testing", "cross browser testing", "compatibility testing"],
    "Security Testing": ["application security testing", "sast", "dast", "vulnerability testing", "app security testing"],
    "Accessibility Testing": ["a11y testing", "wcag testing"],

    # ------------------------------------------------------------------ security
    "Cybersecurity": ["cyber security", "information security", "infosec", "it security", "cyber-security", "security engineering", "cyber security fundamentals",
                      "information security management"],
    "Network Security": ["network security fundamentals", "firewalls", "firewall", "firewall management", "network defense", "network security (firewalls)"],
    "OWASP": ["owasp top 10", "owasp top ten", "owasp top10", "owasp zap", "owasp standards", "web application security"],
    "Penetration Testing": ["pen testing", "pentesting", "pentest", "ethical hacking", "vapt", "vulnerability assessment and penetration testing", "pen test",
                            "penetration tester", "red teaming", "red team"],
    "Vulnerability Assessment": ["vulnerability management", "vulnerability scanning", "vulnerability analysis"],
    "SIEM": ["security information and event management", "siem tools", "siem (splunk)", "log correlation", "security monitoring"],
    "Wireshark": ["wireshark packet analysis", "packet analysis", "packet capture"],
    "Nmap": ["nmap scanning", "network scanning", "port scanning"],
    "Burp Suite": ["burpsuite", "burp", "burp suite professional", "burp suite pro"],
    "Metasploit": ["metasploit framework", "msfconsole"],
    "Kali Linux": ["kali", "kali linux tools"],
    "Incident Response": ["incident handling", "security incident response", "incident response planning"],
    "Intrusion Detection": ["ids", "ips", "ids/ips", "intrusion detection systems", "intrusion prevention", "intrusion detection and prevention"],
    "Cryptography": ["encryption", "pki", "public key infrastructure", "ssl/tls", "tls", "data encryption", "cryptographic algorithms"],
    "Identity and Access Management": ["iam", "identity & access management", "identity management", "access management", "iam (identity and access management)"],
    "Security Operations": ["soc", "security operations center", "soc analyst", "soc operations", "security operations (soc)", "blue team"],
    "Security Compliance": ["compliance", "regulatory compliance", "security compliance", "grc", "audit and compliance"],
    "Threat Modeling": ["threat modelling", "stride", "threat analysis", "attack surface analysis"],

    # ------------------------------------------------------------------ mobile
    "Android Development": ["android", "android sdk", "android studio", "android app development", "android development (kotlin)", "android native", "android apps"],
    "iOS Development": ["ios", "ios app development", "ios development (swift)", "cocoa touch", "ios sdk", "ios apps"],
    "SwiftUI": ["swift ui", "swiftui framework"],
    "UIKit": ["ui kit", "uikit framework"],
    "Jetpack Compose": ["compose multiplatform", "android jetpack compose"],
    "Flutter": ["flutter framework", "flutter sdk", "flutter (dart)", "flutter apps", "flutter app development"],
    "React Native": ["react-native", "reactnative", "react native (expo)", "expo"],
    "Mobile App Development": ["mobile development", "mobile apps", "mobile application development", "app development", "cross-platform development",
                               "cross platform development", "cross-platform mobile development", "hybrid app development"],
    "Xamarin": ["xamarin.forms", "xamarin forms", ".net maui", "maui"],

    # ------------------------------------------------------------------ embedded, electronics, hardware
    "Embedded Systems": ["embedded", "embedded programming", "firmware", "firmware development", "embedded software", "embedded development", "embedded systems design",
                         "embedded firmware"],
    "Embedded C": ["embedded c/c++", "embedded c programming", "embedded c++"],
    "Microcontrollers": ["microcontroller", "mcu", "8051", "8051 microcontroller", "avr", "pic microcontroller", "arm cortex", "arm cortex-m", "microcontroller programming"],
    "Arduino": ["arduino ide", "arduino uno", "arduino programming", "arduino boards"],
    "Raspberry Pi": ["rpi", "raspberrypi", "raspberry pi 4", "raspberry pi programming", "raspbian"],
    "ESP32": ["esp8266", "esp32/esp8266", "esp-idf", "nodemcu"],
    "STM32": ["stm32 microcontrollers", "stm32cube", "stm32cubeide"],
    "RTOS": ["freertos", "real time operating system", "real-time operating system", "real time operating systems", "real-time os", "zephyr rtos"],
    "IoT": ["internet of things", "iot systems", "iot development", "iot applications", "iot protocols", "iot devices"],
    "MQTT": ["mqtt protocol", "mqtt broker", "mosquitto"],
    "I2C": ["i2c protocol", "i²c", "i2c/spi"],
    "SPI": ["spi protocol", "serial peripheral interface"],
    "UART": ["uart communication", "serial communication", "rs232", "rs485"],
    "CAN Bus": ["can protocol", "can communication", "controller area network", "canbus", "can bus protocol"],
    "VLSI": ["vlsi design", "vlsi design flow"],
    "FPGA": ["fpga programming", "fpga design", "fpgas"],
    "PCB Design": ["pcb", "pcb designing", "pcb layout"],
    "Digital Signal Processing": ["dsp", "signal processing", "digital signal processing (dsp)", "audio signal processing", "dsp algorithms"],
    "Simulink": ["matlab/simulink", "matlab simulink", "simulink models"],
    "LabVIEW": ["lab view", "labview programming", "national instruments labview"],
    "Embedded Linux": ["yocto", "buildroot", "device drivers", "linux device drivers", "linux kernel", "kernel development", "bsp"],
    "Robotics": ["ros", "robot operating system", "ros2", "ros 2", "robotics programming", "robotics engineering", "robot programming"],
    "AutoCAD": ["auto cad", "autocad 2d", "autocad drafting"],
    "SolidWorks": ["solid works", "solidworks cad", "solidworks 3d"],
    "CAD": ["computer-aided design", "computer aided design", "3d modeling", "3d modelling"],
    "3D Printing": ["additive manufacturing", "3d printing (fdm)", "fdm printing", "3d printers"],
    "Circuit Analysis": ["circuit simulation"],
    "Power Electronics": ["power electronics design", "smps", "switch mode power supply", "motor drives"],
    "Control Systems": ["control theory", "pid control", "pid controller", "control systems engineering"],
    "Wireless Communication": ["wireless communications"],

    # ------------------------------------------------------------------ blockchain, games, misc tech
    "Blockchain": ["blockchain technology", "blockchain development", "web3", "web3.js"],
    "Unity": ["unity 3d", "unity3d", "unity engine", "unity game development"],
    "Unreal Engine": ["unreal", "ue5", "unreal engine 5", "unreal engine 4", "ue4"],
    "Game Development": ["game dev", "game programming", "game design", "gamedev"],
    "AR/VR": ["augmented reality", "virtual reality", "ar vr", "ar/vr development", "xr", "extended reality", "mixed reality", "arkit", "arcore"],

    # ------------------------------------------------------------------ marketing and sales
    "SEO/SEM Strategy": ["seo", "sem", "search engine optimization", "search engine optimisation", "search engine marketing", "seo/sem", "on-page seo", "off-page seo",
                         "technical seo", "seo optimization", "keyword research", "seo strategy", "link building"],
    "Google Ads": ["google adwords", "adwords", "google ads (adwords)", "google ads campaigns"],
    "Meta Ads Manager": ["meta ads", "facebook ads", "facebook ads manager", "fb ads", "instagram ads", "meta business suite", "facebook advertising", "meta advertising",
                         "facebook & instagram ads", "facebook business manager"],
    "Paid Social": ["paid social media", "paid social advertising", "social media advertising", "social ads", "paid social campaigns"],
    "Social Media Marketing": ["smm", "social media", "social media management", "social media strategy", "social media marketing (smm)", "social media content",
                               "community management", "social media campaigns"],
    "Content Marketing": ["content creation", "blogging", "blog writing", "content writing", "content marketing strategy", "article writing"],
    "Content Strategy": ["content planning", "editorial calendar", "content calendar", "content strategy and planning"],
    "Email Marketing": ["email campaigns", "email marketing campaigns", "email automation", "newsletter marketing", "drip campaigns", "email marketing automation"],
    "Marketing Automation": ["marketing automation tools", "marketing automation platforms", "automation workflows"],
    "HubSpot": ["hubspot crm", "hubspot marketing", "hubspot marketing hub", "hubspot sales hub"],
    "Salesforce": ["sfdc", "salesforce crm", "salesforce.com", "salesforce administration", "salesforce admin", "apex", "salesforce apex"],
    "CRM": ["customer relationship management", "crm software", "crm tools", "crm systems", "crm management"],
    "Mailchimp": ["mailchimp campaigns", "mail chimp"],
    "SEMrush": ["sem rush", "semrush tools"],
    "Ahrefs": ["ahrefs seo", "ahrefs tools"],
    "Google Search Console": ["search console", "gsc", "google webmaster tools", "webmaster tools"],
    "Google Tag Manager": ["google tag manager (gtm)", "tag manager", "tag management"],
    "Copywriting": ["copy writing", "ad copywriting", "copy editing", "marketing copy", "sales copy"],
    "Brand Management": ["branding", "brand strategy", "brand building", "brand development", "brand marketing", "brand positioning"],
    "Influencer Marketing": ["influencer outreach", "influencer campaigns", "influencer partnerships", "creator marketing"],
    "Digital Marketing": ["digital marketing strategy", "online marketing", "internet marketing", "performance marketing", "digital campaigns", "multi-channel digital campaigns",
                         "multichannel marketing", "digital advertising", "online advertising"],
    "Marketing Analytics": ["marketing metrics", "campaign analytics", "campaign reporting", "marketing performance analysis", "marketing reporting", "campaign performance analysis"],
    "ROI/CAC/LTV reporting": ["roi", "cac", "ltv", "roi reporting", "customer acquisition cost", "customer lifetime value", "roas", "marketing roi", "unit economics"],
    "Marketing Budget Management": ["budget ownership", "marketing budget", "campaign budget management", "media budget", "budget allocation", "media planning", "media buying"],
    "Public Relations": ["pr", "media relations", "press releases", "pr strategy", "corporate communications"],
    "Event Management": ["event planning", "events management", "event marketing", "event coordination", "event organization"],
    "Lead Generation": ["lead gen", "leadgen", "lead generation & prospecting", "prospecting", "lead sourcing", "outbound lead generation", "inbound lead generation", "lead qualification"],
    "Cold Calling": ["cold calls", "outbound calling", "telemarketing", "telesales", "outbound sales calls"],
    "B2B Sales": ["b2b", "business-to-business sales", "b2b selling", "b2b marketing", "enterprise sales", "b2b saas sales", "saas sales"],
    "B2C Sales": ["b2c", "retail sales", "direct sales", "consumer sales"],
    "Sales Pipeline Management": ["sales pipeline", "pipeline management", "pipeline generation", "sales funnel", "sales cycle management", "sales forecasting", "deal closing"],
    "Account Management": ["key account management", "kam", "client management", "client relationship management", "customer relationship building", "account handling",
                           "client servicing", "client relations"],
    "Territory Management": ["territory planning", "territory coverage", "area management", "sales territory management"],
    "Customer Service": ["customer support", "customer care", "client support", "customer service excellence", "customer relations", "customer queries handling"],
    "Negotiation Skills": ["negotiation", "contract negotiation", "negotiating", "deal negotiation", "price negotiation"],

    # ------------------------------------------------------------------ finance, accounting
    "Financial Modeling": ["financial modelling", "financial models", "3-statement modeling", "three statement model", "three-statement modeling", "dcf modeling", "financial model building",
                           "lbo modeling", "m&a modeling", "financial forecasting models"],
    "Valuation Methods": ["valuation", "dcf", "dcf valuation", "company valuation", "business valuation", "comparable company analysis", "comps analysis", "precedent transactions",
                          "equity valuation", "valuation analysis", "discounted cash flow"],
    "Financial Analysis": ["financial reporting analysis", "ratio analysis", "financial statement analysis", "financial statements analysis", "fundamental analysis",
                           "financial performance analysis", "financial research"],
    "Financial Reporting": ["financial statements", "financial statement preparation", "management accounts", "mis reports", "monthly reporting", "statutory reporting",
                            "consolidation", "financial close", "month-end close", "month end closing", "month-end closing", "period-end close"],
    "Budgeting": ["budget management", "budgeting & forecasting", "budgeting and forecasting", "budget planning", "budget preparation", "annual budgeting", "budget forecasting"],
    "Rolling Forecasts": ["rolling forecast", "rolling forecasting", "forecast updates"],
    "P&L Analysis": ["p&l", "profit and loss", "profit & loss", "p&l / balance sheet / cash flow analysis", "p and l", "p&l management", "income statement analysis",
                     "p&l ownership", "profit and loss analysis"],
    "Accounting Principles": ["accounting", "gaap", "ifrs", "gaap/ifrs", "us gaap", "ind as", "accounting standards", "financial accounting"],
    "Tally": ["tally erp", "tally prime", "tally erp 9", "tally software", "tally accounting"],
    "QuickBooks": ["quick books", "quickbooks online", "quickbooks accounting"],
    "SAP": ["sap erp", "sap fico", "sap fi/co", "sap s/4hana", "sap s4hana", "sap hana", "sap mm", "sap sd", "sap hcm"],
    "ERP Systems": ["erp", "enterprise resource planning", "erp software", "erp implementation", "erp systems (sap)"],
    "GST": ["goods and services tax", "gst compliance", "gst filing", "gst returns", "gst accounting", "indirect tax"],
    "Taxation": ["tax", "income tax", "tax compliance", "tax planning", "direct tax", "tax filing", "tax preparation", "tds", "tax returns"],
    "Auditing": ["audit", "internal audit", "internal auditing", "statutory audit", "audit procedures", "external audit", "audit and assurance", "audit documentation"],
    "Bloomberg Terminal": ["bloomberg", "bloomberg terminal skills", "bloomberg anywhere"],
    "Accounts Payable/Receivable": ["accounts payable", "accounts receivable", "ap/ar", "ap and ar", "accounts payable and receivable", "payables", "receivables", "invoice processing",
                                    "vendor payments", "billing and collections"],
    "Reconciliation": ["bank reconciliation", "account reconciliation", "reconciliations", "ledger reconciliation", "bank reconciliations"],
    "Investment Analysis": [],
    "Financial Planning": ["fp&a", "fpa", "financial planning and analysis", "financial planning & analysis"],
    "Risk Analysis (Finance)": ["credit risk", "market risk", "financial risk management", "risk modeling", "value at risk", "basel", "basel iii"],
    "CFA Certification": ["cfa", "cfa level 1", "cfa level i", "cfa level 2", "cfa level ii", "cfa level 3", "chartered financial analyst", "cfa charterholder",
                          "cfa level 1 candidate"],

    # ------------------------------------------------------------------ human resources
    "Recruitment": ["recruiting", "talent acquisition", "end-to-end recruitment", "technical recruitment", "it recruitment", "campus recruitment", "talent sourcing", "candidate sourcing", "headhunting", "recruitment and selection", "hiring", "staffing", "bulk hiring", "lateral hiring", "recruitment lifecycle"],
    "Full-Cycle Recruitment": ["full cycle recruitment", "full-cycle recruiting", "full cycle recruiting", "end to end recruiting", "full lifecycle recruiting"],
    "Applicant Tracking Systems": ["ats", "applicant tracking system", "ats tools", "ats platforms"],
    "Interviewing": ["interview scheduling", "conducting interviews", "interview coordination", "behavioral interviewing", "behavioural interviewing", "structured interviews",
                     "candidate screening", "resume screening", "screening", "shortlisting", "candidate assessment"],
    "Onboarding": ["employee onboarding", "new hire onboarding", "onboarding and induction", "induction", "employee induction", "joining formalities", "onboarding process"],
    "Payroll": ["payroll processing", "payroll management", "payroll administration", "salary processing", "payroll compliance", "payroll software"],
    "HRIS Platforms": ["hris", "hr information systems", "hr information system", "hrms", "hr systems", "hr software", "hris systems"],
    "HR Analytics Tools": ["hr analytics/reporting", "hr analytics", "people analytics", "hr analytics reporting", "hr dashboards", "workforce analytics", "hr reporting",
                           "hr data analysis"],
    "HR Metrics Analysis": ["hr metrics", "attrition analysis", "attrition analytics", "turnover analysis", "hr kpis",
                            "time to hire", "cost per hire"],
    "Employee Relations": ["employee grievance handling", "grievance handling", "industrial relations", "disciplinary procedures"],
    "Performance Management": ["performance appraisal", "performance reviews", "performance review", "appraisal process", "kra/kpi", "kra", "goal setting", "performance evaluation",
                               "performance improvement plans", "performance management systems", "360 degree feedback", "360 feedback"],
    "Compensation Benchmarking": ["compensation analysis", "salary benchmarking"],
    "Labor Law Compliance": ["labor law", "labour law", "labor law compliance", "labour law compliance", "employment law", "hr compliance", "statutory compliance",
                             "labour laws", "pf/esi", "pf and esi", "epf", "esi", "shops and establishment act", "posh"],
    "Learning & Development": ["l&d", "training and development", "training & development", "employee training", "training design", "training delivery", "learning and development",
                               "corporate training", "capability building", "lms", "learning management systems", "talent development", "instructional design"],
    "Organizational Development": ["org development", "organization development", "organisational development", "culture building",
                                   "organizational design"],
    "Employer Branding": ["employer brand", "employer branding strategy", "recruitment marketing", "employee value proposition", "evp"],
    "HR Business Partnering": ["hrbp", "hr business partner", "hr partnering", "business partnering", "strategic hr"],

    # ------------------------------------------------------------------ healthcare
    "BLS Certification": ["bls", "basic life support", "bls certified", "bls/acls", "bls provider", "basic life support (bls)", "bls certificate"],
    "ACLS Certification": ["acls", "advanced cardiac life support", "acls certified", "acls provider", "advanced cardiovascular life support", "acls certificate"],
    "Patient Care": ["direct patient care", "bedside care", "patient care management", "nursing care", "patient monitoring"],
    "EMR Systems": ["emr", "ehr", "emr/ehr", "electronic medical records", "electronic health records", "electronic medical records (emr/ehr)", "epic emr", "cerner",
                    "medical records", "hospital information system", "emr documentation", "clinical documentation", "meditech"],
    "Infection Control": ["infection control protocols", "infection prevention", "infection prevention and control", "ipc", "infection control practices", "sterile technique",
                          "aseptic technique", "hand hygiene", "isolation precautions"],
    "Medication Administration": ["medication administration systems", "medication management", "drug administration", "medication safety",
                                  "medication reconciliation"],
    "ICU Nursing": ["icu", "critical care", "critical care nursing", "intensive care", "intensive care unit", "icu care", "icu experience", "critical care experience",
                    "ccu"],
    "Hemodynamic Monitoring": ["hemodynamic monitoring", "haemodynamic monitoring", "invasive monitoring", "swan-ganz"],
    "Clinical Research": ["clinical trials", "clinical trial management", "good clinical practice", "gcp (good clinical practice)", "ich-gcp", "clinical data management"],
    "Healthcare Compliance": ["healthcare regulations", "quality accreditation",
                              "medical ethics", "patient privacy"],
    "RN License": ["registered nurse", "rn", "rn license active", "licensed nurse", "nursing license", "state board license", "nclex"],

    # ------------------------------------------------------------------ operations, office, general
    "Supply Chain Management": ["supply chain", "supply chain operations", "supply chain planning", "demand planning", "demand forecasting", "supply planning", "scm (supply chain)"],
    "Inventory Management": ["inventory control", "stock management", "warehouse management", "inventory planning", "stock control", "wms", "warehousing"],
    "Logistics": ["logistics management", "transportation management", "freight management", "fleet management", "last mile delivery", "shipping and logistics", "distribution"],
    "Procurement": ["purchasing", "vendor management", "supplier management", "vendor development", "strategic sourcing", "supplier negotiation", "purchase orders", "rfp management"],
    "Lean Six Sigma": ["six sigma", "lean", "lean manufacturing", "lean six sigma green belt", "six sigma green belt", "six sigma black belt"],
    "Quality Management": ["qms", "quality management systems", "quality audits"],
    "Microsoft Office": ["ms office", "microsoft office suite", "office 365", "ms-office", "microsoft 365", "m365", "ms office suite", "office suite", "microsoft office 365"],
    "PowerPoint": ["ms powerpoint", "microsoft powerpoint", "ppt", "powerpoint presentations", "presentation design", "google slides", "slide decks", "ms-powerpoint"],
    "Microsoft Word": ["ms word", "word processing", "microsoft word documents"],
    "Google Workspace": ["g suite", "gsuite", "google docs", "google apps", "google drive", "google workspace tools"],
    "Operations Management": ["operations", "business operations", "operations planning", "operational excellence", "operations strategy", "process management"],
    "Teaching": ["classroom teaching", "lesson planning", "curriculum development", "curriculum design", "classroom management", "pedagogy", "instructional design (teaching)",
                 "tutoring", "student assessment", "e-learning development", "course design", "teaching experience"],
    "Legal Research": ["legal drafting", "legal analysis", "case law research", "legal writing"],
    "Research Skills": ["research", "academic research", "literature review", "research methodology", "research and analysis", "qualitative analysis", "quantitative analysis", "quantitative research"],
    "Presentation Skills": ["presentations", "presenting", "client presentations", "pitching", "pitch decks", "investor presentations", "storytelling with data"],

    # ------------------------------------------------------------------ kept separate on purpose: related, but NOT the same skill
    "Amazon ECS": ["ecs", "aws ecs", "amazon ecs", "elastic container service"],
    "Amazon EKS": ["eks", "aws eks", "amazon eks", "elastic kubernetes service"],
    "AWS Fargate": ["fargate"],
    "VMware": ["vsphere", "esxi", "vmware vsphere", "vmware esxi", "vmware workstation"],
    "Hyper-V": ["hyper v", "microsoft hyper-v"],
    "VirtualBox": ["oracle virtualbox", "virtual box"],
    "OpenSearch": ["open search", "aws opensearch"],
    "Firestore": ["cloud firestore", "firebase firestore", "firebase firestore database"],
    "Graph Databases": ["graph database", "graph db"],
    "Xcode": ["xcode ide", "apple xcode"],
    "SystemVerilog": ["system verilog", "systemverilog hdl", "uvm"],
    "Master Data Management": ["mdm", "master data"],
    "Data Quality": ["data validation", "data quality checks", "data quality management", "data profiling"],
    "Data Lineage": ["lineage tracking", "data catalog"],
    "Semantic Search": ["similarity search", "vector search", "neural search", "embedding search"],
    "Agent Frameworks": ["agent framework", "ai agent frameworks", "autogen", "crewai", "crew ai"],
    "Hyperparameter Tuning": ["hyperparameter optimization", "hyper-parameter tuning", "grid search", "optuna", "hyperparameter search"],
    "Fraud Detection": ["fraud analytics", "fraud prevention"],
    "Gradient Boosting": ["gbm", "gradient boosted trees", "gradient boosting machines", "gradient-boosted models"],
    "CatBoost": ["cat boost"],
    "GRU": ["gated recurrent unit", "gated recurrent units", "grus"],
    "Root Cause Analysis": ["rca", "5 whys", "fishbone analysis", "root cause investigation", "root-cause analysis"],
    "Clean Code": ["clean architecture", "clean coding", "coding standards", "best coding practices", "coding best practices", "code quality"],
    "SOLID Principles": ["solid", "solid design principles", "solid (oop)"],
    "Competitive Programming": ["competitive coding", "codeforces", "leetcode", "hackerrank", "codechef"],
    "Audit Logging": ["audit logs", "audit trail", "audit trails", "verification/audit logging", "activity logging"],
    "Locust": ["locust load testing", "locust.io"],
    "k6": ["k6 load testing", "grafana k6"],
    "Gatling": ["gatling load testing"],
    "BrowserStack": ["browser stack", "browserstack automate"],
    "Bugzilla": ["bugzilla tracker"],
    "Digital Forensics": ["forensics", "dfir", "computer forensics", "forensic analysis"],
    "Malware Analysis": ["malware reverse engineering", "reverse engineering", "malware research"],
    "Threat Hunting": ["threat intelligence", "cyber threat hunting", "threat detection"],
    "Endpoint Detection and Response": ["edr", "endpoint security", "endpoint protection", "crowdstrike", "endpoint detection"],
    "Single Sign-On": ["sso", "single sign on", "saml", "saml sso"],
    "Multi-Factor Authentication": ["mfa", "2fa", "two-factor authentication", "two factor authentication", "multi factor authentication"],
    "Active Directory": ["microsoft active directory", "azure active directory", "azure ad", "entra id", "ldap"],
    "GDPR": ["gdpr compliance", "general data protection regulation", "data protection regulations"],
    "HIPAA": ["hipaa compliance", "hipaa regulations", "hipaa privacy"],
    "ISO 27001": ["iso27001", "iso/iec 27001", "iso 27001 compliance", "isms"],
    "SOC 2": ["soc2", "soc 2 compliance", "soc 2 type ii"],
    "PCI DSS": ["pci-dss", "pci compliance", "pci dss compliance"],
    "NIST Framework": ["nist", "nist csf", "nist cybersecurity framework", "nist 800-53", "nist framework"],
    "Altium Designer": ["altium"],
    "KiCad": ["kicad eda"],
    "Xilinx Vivado": ["vivado", "xilinx", "vivado design suite", "xilinx ise"],
    "Intel Quartus": ["quartus", "altera", "quartus prime", "altera quartus"],
    "Digital Design": ["digital logic design", "digital electronics", "digital circuits", "logic design"],
    "RTL Design": ["rtl", "rtl coding", "register transfer level"],
    "ASIC Design": ["asic", "asic design flow", "physical design", "asic verification", "design verification"],
    "Circuit Design": ["analog circuit design", "schematic design", "analog design", "analog electronics"],
    "SPICE Simulation": ["spice", "ltspice", "pspice", "spice simulation tools", "cadence virtuoso"],
    "Multisim": ["ni multisim"],
    "Proteus": ["proteus simulation", "proteus design suite"],
    "PLC Programming": ["plc", "ladder logic", "ladder diagram", "siemens plc", "allen bradley", "plcs"],
    "SCADA": ["scada systems", "scada programming"],
    "HMI": ["hmi design", "human machine interface"],
    "Bluetooth": ["ble", "bluetooth low energy", "bluetooth classic", "bluetooth 5"],
    "LoRaWAN": ["lora communication", "lora wan", "lora radio", "lora iot", "lora networks"],
    "Zigbee": ["zigbee protocol", "zigbee mesh"],
    "Wi-Fi": ["wifi", "wi fi", "802.11", "wireless lan", "wlan"],
    "5G": ["5g nr", "5g networks", "5g technology"],
    "LTE": ["4g lte", "4g", "lte networks"],
    "RF Engineering": ["rf design", "rf", "radio frequency", "rf circuit design", "antenna design", "microwave engineering"],
    "CATIA": ["catia v5", "catia v6"],
    "Creo": ["pro/engineer", "ptc creo", "creo parametric"],
    "Fusion 360": ["autodesk fusion 360", "fusion360"],
    "Ethereum": ["ethereum development", "ethereum blockchain", "eth"],
    "Hyperledger": ["hyperledger fabric", "hyperledger sawtooth"],
    "Smart Contracts": ["smart contract development", "smart contract", "smart contracts development"],
    "Excel VBA": ["vba", "visual basic for applications", "excel macros", "macros", "vba macros", "vba programming"],
    "PPC Advertising": ["ppc", "pay per click", "pay-per-click", "paid search", "ppc campaigns", "paid advertising", "paid media", "sem campaigns",
                        "google ppc", "paid search advertising"],
    "D2C Marketing": ["d2c", "dtc", "direct to consumer", "direct-to-consumer", "d2c brands", "d2c marketing strategy"],
    "FMCG Marketing": ["fmcg", "fast moving consumer goods", "consumer goods marketing", "fmcg sales", "cpg marketing", "cpg"],
    "PESTLE Analysis": ["pestle", "pest analysis", "porters five forces", "porter's five forces", "five forces analysis"],
    "Video Editing": ["video production", "video editing software", "final cut pro", "davinci resolve"],
    "Graphic Design": ["graphic designing", "graphics design", "visual graphics", "creative design"],
    "Creative Writing": ["storytelling", "script writing", "fiction writing"],
    "Technical Support": ["it support", "help desk", "helpdesk", "service desk", "l1 support", "l2 support", "desktop support", "it helpdesk", "technical helpdesk",
                          "application support", "production support"],
    "Customer Success": ["customer success management", "client success", "customer onboarding", "customer retention"],
    "Cross-Functional Collaboration": ["cross functional collaboration", "cross-functional coordination", "cross-functional teams",
                                       "cross functional teams", "cross-functional leadership"],
    "Employee Engagement": ["employee engagement initiatives", "employee retention", "employee welfare", "employee communication", "engagement activities", "employee experience"],
    "Conflict Resolution": ["dispute resolution", "mediation", "conflict management"],
    "Change Management": ["organizational change", "change management (prosci)", "change leadership", "transformation management"],
    "Talent Management": ["talent development planning", "talent review", "talent pipeline management"],
    "HR Generalist": ["hr operations", "hr administration", "hr generalist skills", "hr executive", "general hr"],
    "HR Policies": ["hr policy development", "hr policy", "policy formulation", "employee handbook", "hr policies and procedures"],
    "Compensation & Benefits": ["compensation and benefits", "c&b", "total rewards", "benefits administration", "reward management", "compensation planning",
                                "salary structuring", "compensation management", "employee benefits"],
    "Bookkeeping": ["double entry bookkeeping", "general ledger", "gl accounting", "bookkeeping (tally)", "ledger posting", "journal entries"],
    "Cost Accounting": ["management accounting", "costing", "cost analysis", "standard costing", "cost audit"],
    "Cost Control": ["cost management", "cost reduction", "expense control", "expense management"],
    "Equity Research": ["equity analysis", "securities analysis", "investment research", "stock research", "sell-side research", "buy-side research"],
    "Portfolio Management": ["portfolio analysis", "portfolio construction", "asset management", "wealth management", "investment management"],
    "Investment Banking": ["m&a", "mergers and acquisitions", "ib", "capital markets", "ipo advisory", "deal execution"],
    "Private Equity Experience": ["private equity", "pe experience", "venture capital", "vc experience", "buyouts"],
    "Credit Analysis": ["credit assessment", "credit appraisal", "credit underwriting", "underwriting", "credit evaluation"],
    "Fixed Income": ["bonds", "fixed income securities", "bond analysis", "debt markets"],
    "Treasury Management": ["treasury", "cash management", "treasury operations", "liquidity management"],
    "Cash Flow Management": ["cash flow forecasting", "cash flow analysis", "cash flow planning", "cash forecasting"],
    "Working Capital Management": ["working capital", "working capital analysis", "wc management"],
    "CA (Chartered Accountant)": ["ca", "chartered accountant", "ca inter", "ca final", "ca qualified", "ca (icai)", "icai"],
    "CPA Certification": ["cpa", "certified public accountant", "cpa qualified", "cpa licensed"],
    "ACCA": ["acca qualified", "acca affiliate", "acca member"],
    "CMA Certification": ["cma", "certified management accountant", "cma (usa)", "cma us"],
    "PALS Certification": ["pals", "pediatric advanced life support", "pals certified", "pals provider"],
    "NRP Certification": ["nrp", "neonatal resuscitation program", "nrp certified"],
    "CPR Certification": ["cpr", "cpr certified", "cardiopulmonary resuscitation", "cpr/bls", "cpr certificate"],
    "Patient Assessment": ["health assessment", "physical assessment", "clinical assessment", "nursing assessment", "head-to-toe assessment"],
    "Patient Safety": ["patient safety practices", "patient safety goals", "fall prevention", "safe patient handling"],
    "Arterial Line Care": ["arterial line", "arterial lines", "a-line care", "arterial line management", "arterial line monitoring"],
    "Central Line Care": ["central line", "central venous catheter", "central line management", "cvc care", "picc line care"],
    "ECG Interpretation": ["ecg", "ekg", "ekg interpretation", "cardiac monitoring", "ecg monitoring", "cardiac rhythm interpretation", "telemetry"],
    "Ventilator Management": ["mechanical ventilation", "ventilator care", "vent management", "ventilator weaning", "ventilator settings"],
    "Code Blue Response": ["code blue", "code blue management", "rapid response", "cardiac arrest response", "emergency response"],
    "IV Therapy": ["iv administration", "iv cannulation", "iv insertion", "intravenous therapy", "iv infusion", "venipuncture"],
    "NICU": ["neonatal intensive care", "neonatal nursing", "nicu nursing", "nicu experience"],
    "Emergency Nursing": ["emergency care", "emergency department", "emergency room nursing", "er nursing", "trauma nursing", "triage"],
    "NABH/JCI Experience": ["nabh", "jci", "nabh/jci", "joint commission", "nabh accreditation", "jci accreditation", "nabh and jci"],
    "Pharmacovigilance": ["drug safety", "pv", "safety reporting", "adverse event reporting"],
    "Regulatory Affairs": ["regulatory submissions", "regulatory compliance (pharma)", "fda regulations", "regulatory filings"],
    "Medical Coding": ["icd-10", "icd 10", "icd-10 coding", "cpt coding", "cpt", "medical coder", "hcc coding"],
    "Medical Billing": ["medical billing and coding", "healthcare billing", "revenue cycle management", "rcm", "claims processing"],
    "Process Improvement": ["continuous improvement", "process optimization", "process optimisation", "kaizen", "5s", "process enhancement", "operational improvement"],
    "Quality Control": ["qc", "quality inspection", "quality checks", "inspection", "quality testing (manufacturing)"],
    "GMP": ["good manufacturing practice", "good manufacturing practices", "cgmp", "gmp compliance"],
    "HACCP": ["haccp certified", "food safety", "food safety management", "fssai"],
    "ISO 9001": ["iso9001", "iso 9001:2015", "iso 9001 audit"],
    "Contract Management": ["contract drafting", "contract review", "contract administration", "contracts management", "vendor contracts"],
    "Legal Compliance": ["legal compliance management", "corporate compliance", "regulatory legal compliance", "compliance monitoring"],
    "Report Writing": ["business report writing", "writing reports", "report preparation", "report drafting", "analytical report writing"],
    "Data Collection": ["field data collection", "survey data collection", "data gathering", "survey design", "questionnaire design"],


    # ------------------------------------------------------------------ vendors and techniques kept as their own skills (found while checking real resumes)
    "BSN Degree": ["bsn", "bachelor of science in nursing", "bsn nursing degree", "b.sc nursing", "bsc nursing"],
    "Sensitivity Analysis": ["scenario analysis", "scenario/sensitivity analysis", "sensitivity and scenario analysis", "what-if analysis", "monte carlo simulation"],
    "Variance Analysis": ["budget variance analysis", "variance reporting", "actual vs budget analysis", "bva"],
    "Forecasting": ["financial forecasting", "forecast accuracy", "sales forecasting models", "revenue forecasting"],
    "Workforce Planning": ["headcount planning", "manpower planning", "workforce forecasting", "capacity planning (hr)"],
    "Succession Planning": ["succession management", "leadership succession", "talent succession"],
    "Functional Testing": ["functional tests", "functional test", "feature testing"],
    "LLM API Integration": ["llm integration", "llm apis", "llm api", "integrating llms", "llm sdk integration"],
    "Workday": ["workday hcm", "workday hris", "workday payroll"],
    "BambooHR": ["bamboo hr", "bamboohr hris"],
    "Darwinbox": ["darwinbox hrms"],
    "Keka": ["keka hr", "keka hrms"],
    "Zoho People": ["zoho people hr"],
    "Oracle HCM": ["oracle hcm cloud", "oracle fusion hcm", "oracle hr"],
    "ADP": ["adp workforce now", "adp payroll"],
    "SAP SuccessFactors": ["successfactors", "sap sf", "sap success factors"],
    "Greenhouse": ["greenhouse ats", "greenhouse recruiting"],
    "Lever": ["lever ats", "lever recruiting"],
    "Workable": ["workable ats"],
    "Taleo": ["oracle taleo", "taleo ats"],
    "iCIMS": ["icims ats", "icims talent cloud"],
    "Zoho CRM": ["zoho", "zoho crm plus", "zoho crm administration"],
    "Pipedrive": ["pipedrive crm"],
    "Capital IQ": ["s&p capital iq", "capiq", "cap iq"],
    "FactSet": ["factset research"],
    "Refinitiv": ["refinitiv eikon", "eikon", "thomson reuters eikon"],
    "NetSuite": ["oracle netsuite", "netsuite erp", "netsuite administration"],
    "Microsoft Dynamics": ["dynamics 365", "dynamics crm", "ms dynamics", "microsoft dynamics 365", "dynamics ax"],
    "Oracle ERP": ["oracle fusion", "oracle ebs", "oracle e-business suite", "oracle erp cloud", "oracle applications"],
    "Xero": ["xero accounting"],
    "Zoho Books": ["zoho book"],
    "Looker Studio": ["google data studio", "data studio", "google looker studio", "looker studio dashboards"],
    "Marketo": ["adobe marketo", "marketo engage"],
    "Pardot": ["salesforce pardot", "account engagement"],
    "ActiveCampaign": ["active campaign"],
    "LinkedIn Ads": ["linkedin advertising", "linkedin campaign manager", "linkedin ads manager"],


    "spaCy": ["spacy nlp", "spacy library", "spacy models"],
    "NLTK": ["nltk library", "natural language toolkit"],
    "Relational Databases": ["rdbms", "relational database", "relational database management systems", "relational database management system", "relational dbs"],
    "DevOps": ["dev ops", "devops practices", "devops engineering", "devsecops", "devops culture", "devops tools"],


    "ResNet": ["resnet50", "resnet-50", "resnet18", "resnet101", "residual networks", "residual neural network"],
    "OpenRouter": ["open router", "openrouter api"],
    "Milvus": ["milvus db", "milvus vector database"],
    "pgvector": ["pg vector", "postgres pgvector", "pgvector extension"],


    # ------------------------------------------------------------------ gaps found by checking real resumes and real job requirements
    "Maven": ["apache maven", "maven build", "maven build tool", "pom.xml"],
    "Gradle": ["gradle build", "gradle build tool", "gradle wrapper"],
    "IntelliJ IDEA": ["intellij", "intellij idea ide", "jetbrains intellij", "idea ide"],
    "Eclipse IDE": ["eclipse", "eclipse ide for java", "eclipse java"],
    "Visual Studio Code": ["vs code", "vscode", "visual studio code (vs code)", "vs-code"],
    "Visual Studio": ["ms visual studio", "microsoft visual studio", "visual studio ide"],
    "PyCharm": ["pycharm ide", "jetbrains pycharm"],
    "Stripe": ["stripe api", "stripe payments", "stripe integration"],
    "Razorpay": ["razorpay api", "razorpay payments", "razorpay integration"],
    "PayPal": ["paypal integration", "paypal api"],
    "Payment Gateways": ["payment gateway", "payment gateway integration", "payment integration", "online payments", "payments integration"],
    "SQL Joins": ["joins", "inner join", "left join", "sql join", "table joins", "outer joins"],
    "Window Functions": ["window function", "sql window functions", "analytic functions", "row_number", "window functions (sql)"],
    "CTEs": ["cte", "common table expressions", "common table expression", "with clauses", "recursive cte"],
    "Subqueries": ["sub queries", "nested queries", "subquery", "correlated subqueries", "sql subqueries"],
    "SQL Aggregations": ["aggregations", "aggregate functions", "sql aggregate functions", "group by", "aggregation queries"],
    "AWS Glue": ["glue etl", "aws glue jobs", "glue jobs", "glue crawlers"],
    "Amazon Athena": ["aws athena", "athena queries", "athena sql"],
    "BM25": ["okapi bm25", "bm25 ranking", "bm25 search", "bm25 algorithm"],
    "Hybrid Retrieval (BM25 + Embeddings)": ["hybrid retrieval", "hybrid search", "bm25 + embeddings hybrid search", "hybrid rag", "keyword + semantic search",
                                             "hybrid retrieval (bm25 + embeddings)", "hybrid search (bm25 + embeddings)"],
    "OCR": ["optical character recognition", "ocr pipelines", "text recognition", "document ocr", "ocr (tesseract)"],
    "Tesseract": ["tesseract ocr", "pytesseract", "tesseract-ocr"],
    "Multimodal (Text + Image)": ["multimodal llms", "multimodal ai", "multimodal (text + image)", "multimodal llms (text + image)", "multimodal models", "vision language models",
                                  "vlm", "multimodal"],
    "Structured Output Extraction": ["structured outputs", "structured output", "json extraction", "information extraction", "structured data extraction", "schema-based extraction"],
    "HTTP Methods": ["http verbs", "http protocol", "http", "http requests", "get/post/put/delete", "http status codes"],
    "ASGI": ["asgi servers", "uvicorn", "hypercorn", "daphne"],
    "Django Channels": ["channels (django)", "django channels websockets"],
    "LiveKit": ["live kit", "livekit agents", "livekit sdk"],
    "React Router": ["react-router", "react router dom", "react-router-dom"],
    "React Hook Form": ["react-hook-form", "hook form"],
    "TanStack Query": ["react query", "tanstack react query", "react-query"],
    "Zod": ["zod validation", "zod schemas"],
    "Vercel": ["vercel deployment", "vercel hosting"],
    "Netlify": ["netlify hosting", "netlify deployment"],
    "XAMPP": ["xampp server", "wamp", "lamp stack", "lamp"],
    "Video Processing": ["real-time video processing", "real time video processing", "video analytics", "video stream processing", "video streaming"],
    "Speech Recognition": ["stt", "speech to text", "speech-to-text", "asr", "automatic speech recognition", "whisper", "openai whisper", "voice recognition"],
    "Text-to-Speech": ["tts", "text to speech", "text-to-speech (tts)", "speech synthesis", "voice synthesis"],
    "System Design": ["software architecture", "high level design", "low level design", "hld", "lld", "scalable systems", "scalable architecture", "system architecture",
                      "system design basics", "architecture design", "design of scalable systems"],
    "Distributed Systems": ["distributed computing", "distributed architecture", "distributed system design", "distributed databases"],
    "Team Management": ["people management", "team leadership", "managing teams", "team handling", "team lead", "team building", "team supervision", "leading teams"],
    "MBA": ["master of business administration", "pgdm", "mba qualified", "mba (finance)", "mba (marketing)", "mba (hr)", "post graduate diploma in management"],
    "SaaS Experience": ["saas", "saas industry experience", "software as a service", "saas products", "saas platforms", "saas environment"],
    "CCRN Certification": ["ccrn", "ccrn certified", "ccrn-certified", "critical care registered nurse", "ccrn (adult)"],
    "SHRM-CP Certification": ["shrm-cp", "shrm cp", "shrm-scp", "shrm certified", "shrm certification", "shrm", "sphr", "phr"],
    "Defibrillation": ["defibrillator operation", "defibrillator use", "aed use", "cardioversion", "defibrillators"],
    "Precepting": ["preceptorship", "nursing preceptor", "preceptor", "new nurse orientation", "mentoring nurses"],
    "Career Development": ["career coaching", "career planning", "career pathing", "career development planning", "employee career growth"],
    "Disciplinary Processes": ["disciplinary actions", "disciplinary action", "disciplinary process", "misconduct handling", "show cause notices"],
    "Investigations": ["workplace investigations", "hr investigations", "internal investigations", "complaint investigation", "investigation management"],
    "Agency Management": ["agency relations", "vendor agency management", "staffing agency management", "agency coordination", "recruitment agency management"],
    "DDoS Mitigation": ["ddos", "ddos protection", "ddos attacks", "dos attacks", "ddos defense"],
    "SQL Injection": ["sqli", "sql injection prevention", "sql injection attacks", "injection attacks"],
    "n8n": ["n8n workflow automation", "n8n automation", "n8n.io", "n8n workflows"],
    "Batch Processing": ["batch jobs", "batch inference", "batch processing pipelines", "batch job processing", "bulk processing"],
    "Object Storage": ["s3-compatible object storage", "minio", "cloud storage", "blob storage", "azure blob storage", "google cloud storage", "gcs"],
    "Rate Limiting": ["rate limit", "throttling", "api rate limiting", "request throttling"],
    "Webhooks": ["webhook", "webhook integration", "webhook handling"],
    "Linux Command Line": ["command line", "cli", "command-line", "terminal", "command line interface", "bash commands"],
    "JSON": ["json parsing", "json data", "json schema", "json handling"],
    "XML": ["xml parsing", "xslt", "xml processing", "xpath"],
    "YAML": ["yaml configuration", "yml", "yaml files"],
    "Regular Expressions": ["regex", "regexp", "regular expression", "re module"],
    "Web Scraping": ["web crawling", "scraping", "beautifulsoup", "beautiful soup", "scrapy", "selenium scraping", "data scraping"],
    "Data Annotation": ["data labeling", "data labelling", "labeling tools", "image annotation", "labelimg", "annotation tools"],
    "Excel Dashboards": ["excel dashboard", "dashboards in excel", "excel reporting"],
    "Mentoring": ["mentorship", "coaching", "mentoring juniors", "peer mentoring", "mentoring interns"],

    "Network Engineering": ["network administration", "network design", "cisco networking", "ccna", "ccnp", "network engineer skills"],
}


def build_seed(groups: dict[str, list[str]] = ALIAS_GROUPS) -> dict[str, str]:
    """{lower-case spelling: canonical name}. Raises ValueError when one spelling is claimed by two canonical names."""
    seed: dict[str, str] = {}
    claimed_by: dict[str, str] = {}
    for canonical, variants in groups.items():
        for spelling in [canonical, *variants]:
            key = spelling.strip().lower()
            if not key:
                raise ValueError(f"empty spelling in the group for {canonical!r}")
            if key in claimed_by and claimed_by[key] != canonical:
                raise ValueError(f"the spelling {key!r} is claimed by both {claimed_by[key]!r} and {canonical!r}")
            claimed_by[key] = canonical
            seed[key] = canonical
    return seed


SEED_ALIASES: dict[str, str] = build_seed()
